/** @sim {"name":"One-Change Tuning Experiment Lab","requiresContext":false,"academyApproved":true,"fidelity":"conceptual"} */
import { useMemo, useState } from "react";
import { FlaskConical, RotateCcw } from "lucide-react";

type Direction = "LOWER" | "HIGHER";
type ChangeCount = "ONE" | "MULTIPLE";
export type ExperimentInput = { baseline: number; candidate: number; threshold: number; direction: Direction; changeCount: ChangeCount };
export type ExperimentResult = { classification: "BLOCKED" | "IMPROVED" | "REGRESSED" | "INCONCLUSIVE"; difference: number; next: string };

export function classifyExperiment(input: ExperimentInput): ExperimentResult {
  if (![input.baseline, input.candidate, input.threshold].every(Number.isFinite) || input.threshold <= 0) return { classification: "BLOCKED", difference: 0, next: "Enter finite values and a positive threshold declared before the candidate run." };
  if (input.changeCount !== "ONE") return { classification: "BLOCKED", difference: 0, next: "Return to the baseline and stage exactly one bounded parameter change." };
  const signed = input.direction === "LOWER" ? input.baseline - input.candidate : input.candidate - input.baseline;
  if (signed >= input.threshold) return { classification: "IMPROVED", difference: signed, next: "Check other metrics and limitations before recording accept, revise, reject, or rollback." };
  if (signed <= -input.threshold) return { classification: "REGRESSED", difference: signed, next: "Reject or revise the candidate and preserve the run as evidence." };
  return { classification: "INCONCLUSIVE", difference: signed, next: "Keep the result; revise the question or gather another compatible run without moving the threshold." };
}

const DEFAULTS: ExperimentInput = { baseline: 1.2, candidate: 1.05, threshold: 0.1, direction: "LOWER", changeCount: "ONE" };

export default function SysIdTuningLab() {
  const [input, setInput] = useState(DEFAULTS);
  const result = useMemo(() => classifyExperiment(input), [input]);
  const reset = () => setInput(DEFAULTS);
  return <section aria-labelledby="tuning-experiment-title" className="my-8 rounded-xl border border-ares-cyan/30 bg-black/35 p-4 sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-ares-cyan">Fixed synthetic metric</p><h3 id="tuning-experiment-title" className="mt-1 text-xl font-black text-white">One-Change Tuning Experiment Lab</h3><p className="mt-2 max-w-3xl text-sm leading-relaxed text-marble/80">Classify one invented baseline and candidate using a threshold chosen before the run.</p></div><button type="button" onClick={reset} className="inline-flex min-h-11 items-center justify-center gap-2 rounded border border-white/20 px-4 py-2 text-sm font-bold text-white hover:border-ares-cyan focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ares-cyan"><RotateCcw aria-hidden="true" size={16} /> Reset</button></div><div className="mt-6 grid gap-5 lg:grid-cols-2"><fieldset className="grid gap-4 rounded-lg border border-white/10 bg-white/5 p-4"><legend className="px-2 text-sm font-bold text-ares-gold">Experiment record</legend><NumberField id="tune-baseline" label="Baseline metric (s)" value={input.baseline} onChange={(baseline) => setInput({ ...input, baseline })} /><NumberField id="tune-candidate" label="Candidate metric (s)" value={input.candidate} onChange={(candidate) => setInput({ ...input, candidate })} /><NumberField id="tune-threshold" label="Improvement threshold (s)" value={input.threshold} onChange={(threshold) => setInput({ ...input, threshold })} /><SelectField id="tune-direction" label="Intended direction" value={input.direction} options={["LOWER", "HIGHER"]} onChange={(direction) => setInput({ ...input, direction: direction as Direction })} /><SelectField id="tune-count" label="Parameters changed" value={input.changeCount} options={["ONE", "MULTIPLE"]} onChange={(changeCount) => setInput({ ...input, changeCount: changeCount as ChangeCount })} /></fieldset><div className="rounded-lg border border-white/10 bg-obsidian p-4"><h4 className="flex items-center gap-2 text-sm font-bold uppercase tracking-wider text-ares-gold"><FlaskConical aria-hidden="true" size={18} /> Bounded classification</h4><dl aria-live="polite" aria-atomic="true" className="mt-4 grid gap-3"><Datum label="Result" value={result.classification} /><Datum label="Signed change toward goal" value={`${result.difference.toFixed(2)} s`} /><Datum label="Next action" value={result.next} /></dl></div></div><p role="note" className="mt-5 border-l-4 border-ares-gold/60 bg-ares-gold/10 p-3 text-sm leading-relaxed text-white"><strong>Model limit:</strong> These numbers are invented. This lab does not run SysId, fit a motor model, connect to Studio, apply a parameter, control a simulator or robot, prove causation, certify safety, or promote a tuning profile.</p></section>;
}

function NumberField({ id, label, value, onChange }: { id: string; label: string; value: number; onChange: (value: number) => void }) { return <label htmlFor={id} className="grid gap-2 text-sm font-bold text-white"><span>{label}</span><input id={id} type="number" step="0.01" value={value} onChange={(event) => onChange(event.currentTarget.valueAsNumber)} className="min-h-11 rounded border border-white/20 bg-black px-3 py-2 text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ares-cyan" /></label>; }
function SelectField({ id, label, value, options, onChange }: { id: string; label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <label htmlFor={id} className="grid gap-2 text-sm font-bold text-white"><span>{label}</span><select id={id} value={value} onChange={(event) => onChange(event.currentTarget.value)} className="min-h-11 rounded border border-white/20 bg-black px-3 py-2 text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ares-cyan">{options.map((option) => <option key={option} value={option}>{option.toLowerCase()}</option>)}</select></label>; }
function Datum({ label, value }: { label: string; value: string }) { return <div className="rounded border border-white/10 p-3"><dt className="text-xs uppercase tracking-wide text-marble/70">{label}</dt><dd className="mt-1 font-semibold leading-relaxed text-white">{value}</dd></div>; }
