import { expect,test } from "./fixtures";

test("BIOBUZZ launches browser autos and offers independent timer modes",async({page},testInfo)=>{
  test.setTimeout(65000);
  await page.goto("/biobuzz/simulator");
  await expect(page.getByTestId("inventory")).toContainText("4/4");
  const timer=page.getByRole("timer",{name:"Match timer"});
  const mode=page.getByRole("combobox",{name:"Timer mode",exact:true});
  await expect(mode.locator("option")).toHaveText(["AUTO only · 0:30","TELEOP only · 2:00","Combined · AUTO + TELEOP"]);
  await expect(page.getByRole("button",{name:"Run this auto",exact:true})).toBeDisabled();
  await mode.selectOption("teleop");
  await page.getByRole("button",{name:"Start timed match",exact:true}).click();
  await expect(timer).toContainText("TELEOP");
  const before=await page.getByTestId("robot-position").innerText();
  await page.getByRole("button",{name:"Drive forward",exact:true}).click();
  await expect(page.getByTestId("robot-position")).not.toHaveText(before);
  await expect(page.getByTestId("nectar-countdown")).toContainText("at TELEOP 1:00");
  await page.getByRole("button",{name:"Build an auto",exact:true}).click();
  const editor=page.getByRole("region",{name:"Auto editor",exact:true});
  await expect(editor.getByRole("button",{name:"Run AUTO only",exact:true})).toBeDisabled();
  await editor.getByRole("button",{name:"Add intake",exact:true}).click();
  await editor.getByRole("button",{name:"Add shot",exact:true}).click();
  await editor.getByLabel("Balls",{exact:true}).fill("2");
  await editor.getByLabel("Launch speed (m/s)",{exact:true}).fill("3.08");
  await editor.getByRole("button",{name:"Move step 2 up",exact:true}).click();
  await expect(editor.locator(".bio-steps li").first()).toContainText("1. shoot");
  await editor.getByRole("button",{name:"Move step 1 down",exact:true}).click();
  await expect(editor.locator(".bio-steps li").first()).toContainText("1. intake");
  await editor.getByRole("checkbox",{name:"Intake enabled",exact:true}).uncheck();
  await editor.getByRole("button",{name:"Run AUTO only",exact:true}).click();
  await expect(mode).toHaveValue("auto");
  await expect(timer).toContainText("AUTO");
  await expect(page.getByTestId("nectar-countdown")).toContainText("stays locked throughout AUTO");
  await expect(page.getByTestId("inventory")).toContainText("2/4");
  await page.getByRole("button",{name:"Pause",exact:true}).click();
  await expect(timer).toContainText("PAUSED");
  await testInfo.attach("auto-controls",{body:await editor.screenshot(),contentType:"image/png"});
  await page.getByRole("button",{name:"Resume",exact:true}).click();
  await expect(timer).toContainText("FINISHED",{timeout:35000});
  await mode.selectOption("combined");
  await page.getByRole("button",{name:"Run this auto",exact:true}).click();
  await expect(timer).toContainText("AUTO");
  await expect(page.getByTestId("inventory")).toContainText("2/4");
  await expect(page.getByTestId("nectar-countdown")).toContainText("at TELEOP 1:00");
  await page.getByRole("button",{name:"Return to untimed practice",exact:true}).click();
  await expect(timer).toContainText("PRACTICE");
  await expect(page.getByTestId("inventory")).toContainText("4/4");
});
