import { expect, test } from "./fixtures";

test("BIOBUZZ computes a match, shared flowers, event RP, and reversible reset", async ({ page }, testInfo) => {
  await page.goto("/biobuzz/score-calculator");
  await expect(page.getByRole("heading", { level: 1 })).toContainText("BIOBUZZ");
  const red = page.getByRole("region", { name: "Red scoring", exact: true });
  const blue = page.getByRole("region", { name: "Blue scoring", exact: true });
  await red.getByLabel("Robots that LEAVE", { exact: true }).fill("2");
  await red.getByLabel("Robots parked in AUTO", { exact: true }).fill("2");
  await red.getByLabel("AUTO HIVE tips", { exact: true }).fill("2");
  await red.getByLabel("TELEOP HIVE tips", { exact: true }).fill("5");
  await blue.getByLabel("Minor fouls committed", { exact: true }).fill("1");
  const flower = page.getByRole("region", { name: "Flower 1", exact: true });
  await flower.getByRole("button", { name: "+ Red nectar", exact: true }).click();
  await flower.getByRole("button", { name: "+ Pollen", exact: true }).click();
  await flower.getByRole("button", { name: "+ Blue nectar", exact: true }).click();
  await expect(page.getByLabel("Red score: 166", { exact: true })).toBeVisible();
  await expect(page.getByLabel("Blue score: 6", { exact: true })).toBeVisible();
  await expect(page.getByText("6 / 6 RP", { exact: true })).toBeVisible();
  await flower.getByRole("button", { name: "Remove Blue at position 3" }).click();
  await expect(page.getByLabel("Red score: 170", { exact: true })).toBeVisible();
  await page.getByLabel("RP thresholds", { exact: true }).selectOption("championship");
  await expect(page.getByText(/Regional and FIRST Championship thresholds are TBA/)).toBeVisible();
  await expect(page.getByText("— / 6 RP · thresholds needed")).toHaveCount(2);
  await page.getByLabel("RP thresholds", { exact: true }).selectOption("custom");
  await page.getByLabel("SWARM points", { exact: true }).fill("16");
  await page.getByLabel("POLLINATOR 1 tips", { exact: true }).fill("4");
  await page.getByLabel("POLLINATOR 2 tips", { exact: true }).fill("8");
  await expect(page.getByText("5 / 6 RP", { exact: true })).toBeVisible();
  await red.getByLabel("Robots that LEAVE", { exact: true }).fill("3");
  await expect(page.getByRole("alert")).toContainText("Check the match entries");
  await expect(page.getByLabel("Red score: incomplete", { exact: true })).toBeVisible();
  await red.getByLabel("Robots that LEAVE", { exact: true }).fill("2");
  await page.getByRole("button", { name: "Reset match", exact: true }).click();
  await expect(page.getByLabel("Red score: 0", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Undo reset", exact: true }).click();
  await expect(page.getByLabel("Red score: 170", { exact: true })).toBeVisible();
  await page.getByLabel("Match type", { exact: true }).selectOption("playoff");
  await expect(page.getByText("Total RP", { exact: true })).toHaveCount(0);
  await page.setViewportSize({ width: 320, height: 900 });
  await red.getByLabel("AUTO HIVE tips", { exact: true }).fill("9999");
  const largeScore = page.getByLabel("Red score: 200110", { exact: true });
  await expect(largeScore).toBeVisible();
  expect(await largeScore.evaluate(element => {
    const range = document.createRange();
    range.selectNodeContents(element);
    return range.getBoundingClientRect().width <= element.clientWidth;
  })).toBe(true);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await red.getByLabel("AUTO HIVE tips", { exact: true }).fill("2");
  await page.screenshot({ path: `scratch/biobuzz/mobile-${testInfo.project.name}.png`, fullPage: true });
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.screenshot({ path: `scratch/biobuzz/desktop-${testInfo.project.name}.png`, fullPage: true });
});

test("BIOBUZZ is reachable from Resources using keyboard navigation", async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.goto("/");
  const nav = page.getByRole("navigation", { name: "Main Navigation" });
  const resources = nav.getByRole("button", { name: "Resources", exact: true });
  await resources.focus();
  await page.keyboard.press("Enter");
  const link = nav.getByRole("link", { name: "BIOBUZZ Score Calculator", exact: true });
  await expect(link).toBeVisible();
  await link.focus();
  await page.keyboard.press("Enter");
  await expect(page).toHaveURL(/\/biobuzz\/score-calculator$/);
  await expect(page.getByRole("heading", { level: 1 })).toBeFocused();
});
