import { expect,test } from "./fixtures";
import { mkdir } from "node:fs/promises";
import JSZip from "jszip";
import { readFile } from "node:fs/promises";

test("BIOBUZZ solo driving, native auto export, and an actual hive tip",async({page},testInfo)=>{
  test.setTimeout(60000);
  await page.goto("/biobuzz/simulator");
  await expect(page.getByTestId("inventory")).toContainText("4/4");
  await expect(page.getByRole("combobox",{name:"Controlled robot",exact:true}).locator("option")).toHaveCount(1);
  const before=await page.getByTestId("robot-position").innerText();
  await page.getByRole("button",{name:"Drive right",exact:true}).click();
  await expect(page.getByTestId("robot-position")).not.toHaveText(before);
  await page.getByRole("button",{name:"Reset local field",exact:true}).click();
  await page.getByRole("button",{name:"Build an auto",exact:true}).click();
  const editor=page.getByRole("region",{name:"Auto editor",exact:true});
  await editor.getByLabel("Auto name",{exact:true}).fill("Browser hive auto");
  await editor.getByRole("button",{name:"Add waypoint",exact:true}).click();
  await editor.getByLabel("X (m)",{exact:true}).nth(1).fill("-1.48");
  await editor.getByLabel("Y (m)",{exact:true}).nth(1).fill("1.48");
  await editor.getByLabel("Heading (rad)",{exact:true}).nth(1).fill("-0.7918");
  await editor.getByRole("button",{name:"Add wait",exact:true}).click();
  await editor.getByRole("button",{name:"Add intake",exact:true}).click();
  await editor.getByRole("checkbox",{name:"Intake enabled",exact:true}).uncheck();
  await editor.getByRole("button",{name:"Add shot",exact:true}).click();
  await editor.getByLabel("Balls",{exact:true}).fill("4");
  await editor.getByLabel("Launch speed (m/s)",{exact:true}).fill("5.46");
  await editor.getByRole("button",{name:"Add waypoint",exact:true}).click();
  await editor.getByLabel("X (m)",{exact:true}).nth(2).fill("-0.59417");
  await editor.getByLabel("Y (m)",{exact:true}).nth(2).fill("1.33");
  await editor.getByLabel("Heading (rad)",{exact:true}).nth(2).fill("1.5708");
  await editor.getByRole("button",{name:"Add intake",exact:true}).click();
  await editor.getByRole("button",{name:"Add wait",exact:true}).click();
  await editor.getByLabel("Seconds",{exact:true}).nth(1).fill("2");
  await editor.getByRole("button",{name:"Save locally",exact:true}).click();
  const downloaded=page.waitForEvent("download");
  await editor.getByRole("button",{name:"Export for ARES Studio",exact:true}).click();
  await mkdir("scratch/biobuzz",{recursive:true});
  const destination=`scratch/biobuzz/browser-auto-${testInfo.project.name}.zip`;
  await (await downloaded).saveAs(destination);
  const zip=await JSZip.loadAsync(await readFile(destination));
  const catalog=JSON.parse(await zip.file(".ares/autonomous-catalog.json")!.async("string"));
  expect(catalog.entries[0]).toMatchObject({authoredAlliance:"RED",mirrorForOppositeAlliance:false,startingPose:{xMeters:-1.1,yMeters:1.8288-Math.hypot(0.225,0.225)}});
  await editor.getByRole("button",{name:"Preview auto",exact:true}).click();
  await expect(page.getByTestId("match-clock")).toContainText("AUTO");
  await expect(page.getByText(/^red hive: 1 tips/)).toBeVisible({timeout:15000});
  await expect(page.getByTestId("inventory")).toContainText("4/4",{timeout:20000});
  await expect(page.getByText("Flower 2: 0 pollen / 0 nectar",{exact:true})).toBeVisible();
  await page.getByRole("button",{name:"Close auto editor",exact:true}).click();
  await page.screenshot({path:`scratch/biobuzz/browser-hive-tip-${testInfo.project.name}.png`,fullPage:true});
  await page.getByRole("button",{name:"Solo, no bots",exact:true}).click();
  await expect(page.getByTestId("match-clock")).toContainText("PRACTICE");
  await expect(page.getByTestId("inventory")).toContainText("4/4");
});
