/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface _CfMETADATA {
  key: Generated<number | null>;
  value: Uint8Array | null;
}

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: number | null;
  accountId: string;
  createdAt: number;
  id: string | null;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: number | null;
  scope: string | null;
  updatedAt: number;
  userId: string;
}

export interface AuditLog {
  action: string;
  actor: string;
  created_at: Generated<string | null>;
  details: string | null;
  id: string | null;
  resource_id: string | null;
  resource_type: string;
}

export interface Awards {
  created_at: Generated<string | null>;
  date: string;
  description: string | null;
  event_name: string;
  icon_type: Generated<string | null>;
  id: Generated<number | null>;
  id_new: string | null;
  is_deleted: Generated<number | null>;
  season_id: string | null;
  title: string;
}

export interface Badges {
  color_theme: Generated<string | null>;
  created_at: Generated<string | null>;
  description: string | null;
  icon: Generated<string | null>;
  id: string | null;
  name: string;
}

export interface Comments {
  content: string;
  created_at: Generated<string | null>;
  id: Generated<number | null>;
  is_deleted: Generated<number | null>;
  target_id: string;
  target_type: string;
  user_id: string;
  zulip_message_id: string | null;
  zulip_sender_id: number | null;
}

export interface D1Migrations {
  applied_at: Generated<string>;
  id: Generated<number | null>;
  name: string | null;
}

export interface Docs {
  category: string;
  cf_email: string | null;
  content: string;
  description: string | null;
  is_deleted: Generated<number | null>;
  is_executive_summary: Generated<number | null>;
  is_portfolio: Generated<number | null>;
  revision_of: string | null;
  slug: string | null;
  sort_order: Generated<number | null>;
  status: Generated<string | null>;
  title: string;
  updated_at: Generated<string | null>;
}

export interface DocsFeedback {
  comment: string | null;
  created_at: Generated<string | null>;
  id: Generated<number | null>;
  is_helpful: number;
  slug: string;
}

export interface DocsFts {
  category: string | null;
  content: string | null;
  description: string | null;
  is_deleted: string | null;
  slug: string | null;
  status: string | null;
  title: string | null;
}

export interface DocsFtsConfig {
  k: string;
  v: string | null;
}

export interface DocsFtsContent {
  c0: string | null;
  c1: string | null;
  c2: string | null;
  c3: string | null;
  c4: string | null;
  c5: string | null;
  c6: string | null;
  id: Generated<number | null>;
}

export interface DocsFtsData {
  block: Uint8Array | null;
  id: Generated<number | null>;
}

export interface DocsFtsDocsize {
  id: Generated<number | null>;
  sz: Uint8Array | null;
}

export interface DocsFtsIdx {
  pgno: string | null;
  segid: string;
  term: string;
}

export interface DocsHistory {
  author_email: string | null;
  category: string;
  content: string;
  created_at: Generated<string | null>;
  description: string | null;
  id: Generated<number | null>;
  slug: string;
  title: string;
}

export interface Events {
  category: Generated<string | null>;
  cf_email: string | null;
  cover_image: string | null;
  date_end: string | null;
  date_start: string;
  description: string | null;
  gcal_event_id: string | null;
  id: string | null;
  is_deleted: Generated<number | null>;
  is_potluck: Generated<number | null>;
  is_volunteer: Generated<number | null>;
  location: string | null;
  published_at: string | null;
  revision_of: string | null;
  season_id: string | null;
  status: Generated<string | null>;
  tba_event_key: string | null;
  title: string;
}

export interface EventsFts {
  description: string | null;
  id: string | null;
  is_deleted: string | null;
  location: string | null;
  status: string | null;
  title: string | null;
}

export interface EventsFtsConfig {
  k: string;
  v: string | null;
}

export interface EventsFtsContent {
  c0: string | null;
  c1: string | null;
  c2: string | null;
  c3: string | null;
  c4: string | null;
  c5: string | null;
  id: Generated<number | null>;
}

export interface EventsFtsData {
  block: Uint8Array | null;
  id: Generated<number | null>;
}

export interface EventsFtsDocsize {
  id: Generated<number | null>;
  sz: Uint8Array | null;
}

export interface EventsFtsIdx {
  pgno: string | null;
  segid: string;
  term: string;
}

export interface EventSignups {
  attended: Generated<number | null>;
  bringing: string | null;
  created_at: Generated<string | null>;
  event_id: string;
  id: Generated<number | null>;
  notes: string | null;
  prep_hours: Generated<number | null>;
  user_id: string;
}

export interface Inquiries {
  created_at: Generated<string | null>;
  email: string;
  id: string | null;
  metadata: string | null;
  name: string;
  status: Generated<string | null>;
  type: string;
}

export interface JudgeAccessCodes {
  code: string | null;
  created_at: Generated<string | null>;
  expires_at: string | null;
  id: string | null;
}

export interface Locations {
  address: string;
  created_at: Generated<string | null>;
  id: string | null;
  is_deleted: Generated<number | null>;
  maps_url: string | null;
  name: string;
}

export interface MediaTags {
  folder: string | null;
  key: string | null;
  tags: string | null;
}

export interface Notifications {
  created_at: Generated<string | null>;
  id: string | null;
  is_read: Generated<number | null>;
  link: string | null;
  message: string;
  priority: Generated<string | null>;
  title: string;
  user_id: string;
}

export interface OutreachLogs {
  cf_email: string | null;
  created_at: Generated<string | null>;
  date: string;
  hours: number | null;
  id: Generated<number | null>;
  impact_summary: string | null;
  is_deleted: Generated<number | null>;
  location: string | null;
  people_reached: number | null;
  season_id: string | null;
  students_count: Generated<number | null>;
  title: string;
}

export interface PageAnalytics {
  category: string;
  id: Generated<number | null>;
  path: string;
  referrer: string | null;
  timestamp: Generated<string | null>;
  user_agent: string | null;
}

export interface Posts {
  ast: string | null;
  author: string | null;
  cf_email: string | null;
  date: string | null;
  is_deleted: Generated<number | null>;
  is_portfolio: Generated<number | null>;
  published_at: string | null;
  revision_of: string | null;
  season_id: string | null;
  slug: string | null;
  snippet: string | null;
  status: Generated<string | null>;
  thumbnail: string | null;
  title: string | null;
}

export interface PostsFts {
  ast: string | null;
  author: string | null;
  is_deleted: string | null;
  slug: string | null;
  snippet: string | null;
  status: string | null;
  title: string | null;
}

export interface PostsFtsConfig {
  k: string;
  v: string | null;
}

export interface PostsFtsContent {
  c0: string | null;
  c1: string | null;
  c2: string | null;
  c3: string | null;
  c4: string | null;
  c5: string | null;
  c6: string | null;
  id: Generated<number | null>;
}

export interface PostsFtsData {
  block: Uint8Array | null;
  id: Generated<number | null>;
}

export interface PostsFtsDocsize {
  id: Generated<number | null>;
  sz: Uint8Array | null;
}

export interface PostsFtsIdx {
  pgno: string | null;
  segid: string;
  term: string;
}

export interface PostsHistory {
  ast: string;
  author: string | null;
  author_email: string | null;
  created_at: Generated<string | null>;
  id: Generated<number | null>;
  season_id: string | null;
  slug: string;
  snippet: string | null;
  thumbnail: string | null;
  title: string;
}

export interface RateLimits {
  count: number;
  expires_at: number;
  ip: string | null;
}

export interface Seasons {
  album_cover: string | null;
  album_url: string | null;
  challenge_name: string;
  created_at: Generated<string | null>;
  end_year: number | null;
  is_deleted: Generated<number | null>;
  robot_cad_url: string | null;
  robot_description: string | null;
  robot_image: string | null;
  robot_name: string | null;
  start_year: Generated<number | null>;
  status: Generated<string | null>;
  summary: string | null;
  updated_at: Generated<string | null>;
}

export interface Session {
  createdAt: number;
  expiresAt: number;
  id: string | null;
  ipAddress: string | null;
  token: string;
  updatedAt: number;
  userAgent: string | null;
  userId: string;
}

export interface Settings {
  key: string | null;
  updated_at: Generated<string | null>;
  value: string;
}

export interface SponsorMetrics {
  clicks: Generated<number | null>;
  created_at: Generated<string | null>;
  id: string | null;
  impressions: Generated<number | null>;
  sponsor_id: string;
  year_month: string;
}

export interface Sponsors {
  created_at: Generated<string | null>;
  id: string | null;
  is_active: Generated<number | null>;
  logo_url: string | null;
  name: string;
  tier: string;
  website_url: string | null;
}

export interface SponsorTokens {
  created_at: Generated<string | null>;
  created_by: string | null;
  sponsor_id: string;
  token: string | null;
}

export interface User {
  createdAt: number;
  email: string;
  emailVerified: number;
  id: string | null;
  image: string | null;
  name: string;
  role: Generated<string | null>;
  updatedAt: number;
}

export interface UserBadges {
  awarded_at: Generated<string | null>;
  awarded_by: string | null;
  badge_id: string;
  id: Generated<number | null>;
  user_id: string;
}

export interface UserProfiles {
  bio: string | null;
  colleges: Generated<string | null>;
  contact_email: string | null;
  dietary_restrictions: string | null;
  emergency_contact_name: string | null;
  emergency_contact_phone: string | null;
  employers: Generated<string | null>;
  favorite_first_thing: string | null;
  favorite_food: string | null;
  favorite_robot_mechanism: string | null;
  first_name: string | null;
  fun_fact: string | null;
  grade_year: string | null;
  last_name: string | null;
  leadership_role: string | null;
  member_type: Generated<string | null>;
  nickname: string | null;
  parents_email: string | null;
  parents_name: string | null;
  phone: string | null;
  pre_match_superstition: string | null;
  pronouns: string | null;
  rookie_year: string | null;
  show_email: Generated<number | null>;
  show_on_about: Generated<number | null>;
  show_phone: Generated<number | null>;
  students_email: string | null;
  students_name: string | null;
  subteams: Generated<string | null>;
  tshirt_size: string | null;
  updated_at: Generated<string | null>;
  user_id: string | null;
}

export interface UserProfilesFts {
  bio: string | null;
  first_name: string | null;
  last_name: string | null;
  nickname: string | null;
  show_on_about: string | null;
  user_id: string | null;
}

export interface UserProfilesFtsConfig {
  k: string;
  v: string | null;
}

export interface UserProfilesFtsContent {
  c0: string | null;
  c1: string | null;
  c2: string | null;
  c3: string | null;
  c4: string | null;
  c5: string | null;
  id: Generated<number | null>;
}

export interface UserProfilesFtsData {
  block: Uint8Array | null;
  id: Generated<number | null>;
}

export interface UserProfilesFtsDocsize {
  id: Generated<number | null>;
  sz: Uint8Array | null;
}

export interface UserProfilesFtsIdx {
  pgno: string | null;
  segid: string;
  term: string;
}

export interface Verification {
  createdAt: number | null;
  expiresAt: number;
  id: string | null;
  identifier: string;
  updatedAt: number | null;
  value: string;
}

export interface DB {
  _cf_METADATA: _CfMETADATA;
  account: Account;
  audit_log: AuditLog;
  awards: Awards;
  badges: Badges;
  comments: Comments;
  d1_migrations: D1Migrations;
  docs: Docs;
  docs_feedback: DocsFeedback;
  docs_fts: DocsFts;
  docs_fts_config: DocsFtsConfig;
  docs_fts_content: DocsFtsContent;
  docs_fts_data: DocsFtsData;
  docs_fts_docsize: DocsFtsDocsize;
  docs_fts_idx: DocsFtsIdx;
  docs_history: DocsHistory;
  event_signups: EventSignups;
  events: Events;
  events_fts: EventsFts;
  events_fts_config: EventsFtsConfig;
  events_fts_content: EventsFtsContent;
  events_fts_data: EventsFtsData;
  events_fts_docsize: EventsFtsDocsize;
  events_fts_idx: EventsFtsIdx;
  inquiries: Inquiries;
  judge_access_codes: JudgeAccessCodes;
  locations: Locations;
  media_tags: MediaTags;
  notifications: Notifications;
  outreach_logs: OutreachLogs;
  page_analytics: PageAnalytics;
  posts: Posts;
  posts_fts: PostsFts;
  posts_fts_config: PostsFtsConfig;
  posts_fts_content: PostsFtsContent;
  posts_fts_data: PostsFtsData;
  posts_fts_docsize: PostsFtsDocsize;
  posts_fts_idx: PostsFtsIdx;
  posts_history: PostsHistory;
  rate_limits: RateLimits;
  seasons: Seasons;
  session: Session;
  settings: Settings;
  sponsor_metrics: SponsorMetrics;
  sponsor_tokens: SponsorTokens;
  sponsors: Sponsors;
  user: User;
  user_badges: UserBadges;
  user_profiles: UserProfiles;
  user_profiles_fts: UserProfilesFts;
  user_profiles_fts_config: UserProfilesFtsConfig;
  user_profiles_fts_content: UserProfilesFtsContent;
  user_profiles_fts_data: UserProfilesFtsData;
  user_profiles_fts_docsize: UserProfilesFtsDocsize;
  user_profiles_fts_idx: UserProfilesFtsIdx;
  verification: Verification;
}
