/** @sim {"name":"Fault Tree Isolation Lab","requiresContext":false,"academyApproved":true,"fidelity":"conceptual"} */
import { useMemo, useState } from "react";
import { GitBranch, RotateCcw } from "lucide-react";

type RequestEvidence = "UNKNOWN" | "CHANGED" | "NOT_CHANGED";
type WriteEvidence = "UNKNOWN" | "SUCCEEDED" | "FAILED";
type MotionEvidence = "UNKNOWN" | "MOVED" | "STILL";
type CurrentEvidence = "UNKNOWN" | "NORMAL" | "HIGH";
export type FaultEvidence = { request: RequestEvidence; write: WriteEvidence; motion: MotionEvidence; current: CurrentEvidence };
export type FaultAnalysis = { observation: string; openBranches: string[]; nextTest: string };

export function analyzeFaultEvidence(evidence: FaultEvidence): FaultAnalysis {
  if (evidence.request === "UNKNOWN") return { observation: "The request path has not been observed.", openBranches: ["input or state", "output path", "device or mechanism"], nextTest: "Keep outputs neutral and record whether the requested target changes." };
  if (evidence.request === "NOT_CHANGED") return { observation: "The requested target did not change.", openBranches: ["input mapping", "action or reducer", "guard or interlock"], nextTest: "Use a safe software test to trace input, action, state, and the blocking guard." };
  if (evidence.write === "UNKNOWN") return { observation: "The target changed, but output-write evidence is missing.", openBranches: ["output adapter", "device identity", "power or communication"], nextTest: "Keep disabled and inspect the cached output command and reported write result." };
  if (evidence.write === "FAILED") return { observation: "The output adapter reported a failed write.", openBranches: ["device identity", "communication", "adapter fault"], nextTest: "Preserve the failure, command neutral, and check topology and startup health." };
  if (evidence.motion === "UNKNOWN") return { observation: "The target and write changed, but motion evidence is missing.", openBranches: ["sensor evidence", "wiring or power", "physical mechanism"], nextTest: "Choose one restrained observation that separates sensor evidence from physical motion." };
  if (evidence.motion === "MOVED") return { observation: "Recorded motion changed after a successful write.", openBranches: ["intermittent fault", "wrong scale or direction", "original report context"], nextTest: "Repeat the same bounded test and compare timestamps, units, direction, and stop behavior." };
  if (evidence.current === "UNKNOWN") return { observation: "Position stayed still, and current evidence is missing.", openBranches: ["unpowered or disconnected output", "jam or load", "invalid position signal"], nextTest: "Keep the robot restrained and capture valid current plus an independent motion observation." };
  if (evidence.current === "HIGH") return { observation: "Position stayed still while measured current was high.", openBranches: ["jam or blocked mechanism", "excess load", "incorrect current or position evidence"], nextTest: "Stop output, inspect safely, and test the competing sensor-evidence explanation before naming a cause." };
  return { observation: "Position stayed still while measured current was not high.", openBranches: ["unpowered output", "disconnected mechanism", "invalid current or position evidence"], nextTest: "Check power and connection evidence without bypassing neutral or stop controls." };
}

const DEFAULTS: FaultEvidence = { request: "UNKNOWN", write: "UNKNOWN", motion: "UNKNOWN", current: "UNKNOWN" };

export default function FaultTreeLab() {
  const [evidence, setEvidence] = useState(DEFAULTS);
  const analysis = useMemo(() => analyzeFaultEvidence(evidence), [evidence]);
  const reset = () => setEvidence(DEFAULTS);
  return <section aria-labelledby="fault-tree-title" className="my-8 rounded-xl border border-ares-cyan/30 bg-black/35 p-4 sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-ares-cyan">One symptom, several branches</p><h3 id="fault-tree-title" className="mt-1 text-xl font-black text-white">Fault Tree Isolation Lab</h3><p className="mt-2 max-w-3xl text-sm leading-relaxed text-marble/80">Add invented evidence for a mechanism that does not move. The model narrows possible branches without declaring a root cause.</p></div><button type="button" onClick={reset} className="inline-flex min-h-11 items-center justify-center gap-2 rounded border border-white/20 px-4 py-2 text-sm font-bold text-white hover:border-ares-cyan focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ares-cyan"><RotateCcw aria-hidden="true" size={16} /> Reset</button></div><div className="mt-6 grid gap-5 lg:grid-cols-2"><fieldset className="grid gap-4 rounded-lg border border-white/10 bg-white/5 p-4"><legend className="px-2 text-sm font-bold text-ares-gold">Invented evidence</legend><SelectField id="fault-request" label="Requested target" value={evidence.request} options={["UNKNOWN", "CHANGED", "NOT_CHANGED"]} onChange={(request) => setEvidence({ ...evidence, request: request as RequestEvidence })} /><SelectField id="fault-write" label="Output write" value={evidence.write} options={["UNKNOWN", "SUCCEEDED", "FAILED"]} onChange={(write) => setEvidence({ ...evidence, write: write as WriteEvidence })} /><SelectField id="fault-motion" label="Recorded motion" value={evidence.motion} options={["UNKNOWN", "MOVED", "STILL"]} onChange={(motion) => setEvidence({ ...evidence, motion: motion as MotionEvidence })} /><SelectField id="fault-current" label="Measured current" value={evidence.current} options={["UNKNOWN", "NORMAL", "HIGH"]} onChange={(current) => setEvidence({ ...evidence, current: current as CurrentEvidence })} /></fieldset><div className="rounded-lg border border-white/10 bg-obsidian p-4"><h4 className="flex items-center gap-2 text-sm font-bold uppercase tracking-wider text-ares-gold"><GitBranch aria-hidden="true" size={18} /> Current tree result</h4><dl aria-live="polite" aria-atomic="true" className="mt-4 grid gap-3"><Datum label="Observation" value={analysis.observation} /><Datum label="Open branches" value={analysis.openBranches.join("; ")} /><Datum label="Smallest safe next test" value={analysis.nextTest} /></dl></div></div><p role="note" className="mt-5 border-l-4 border-ares-gold/60 bg-ares-gold/10 p-3 text-sm leading-relaxed text-white"><strong>Model limit:</strong> The selections are invented. This lab does not read robot state, inspect wiring or power, move a mechanism, verify a sensor, identify a root cause, authorize output, or prove a repair.</p></section>;
}

function SelectField({ id, label, value, options, onChange }: { id: string; label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <label htmlFor={id} className="grid gap-2 text-sm font-bold text-white"><span>{label}</span><select id={id} value={value} onChange={(event) => onChange(event.currentTarget.value)} className="min-h-11 rounded border border-white/20 bg-black px-3 py-2 text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ares-cyan">{options.map((option) => <option key={option} value={option}>{option.replaceAll("_", " ").toLowerCase()}</option>)}</select></label>; }
function Datum({ label, value }: { label: string; value: string }) { return <div className="rounded border border-white/10 p-3"><dt className="text-xs uppercase tracking-wide text-marble/70">{label}</dt><dd className="mt-1 font-semibold leading-relaxed text-white">{value}</dd></div>; }
