/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface _CfMETADATA {
  key: Generated<number | null>;
  value: Uint8Array | null;
}

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: number | null;
  accountId: string;
  createdAt: number;
  id: string | null;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: number | null;
  scope: string | null;
  updatedAt: number;
  userId: string;
}

export interface AuditLog {
  action: string;
  actor: string;
  created_at: Generated<string | null>;
  details: string | null;
  id: string | null;
  resource_id: string | null;
  resource_type: string;
}

export interface Awards {
  created_at: Generated<string | null>;
  date: string;
  description: string | null;
  event_name: string;
  icon_type: Generated<string | null>;
  id: Generated<number | null>;
  is_deleted: Generated<number | null>;
  season_id: number | null;
  title: string;
}

export interface AwardsFts {
  description: string | null;
  event_name: string | null;
  title: string | null;
}

export interface AwardsFtsConfig {
  k: string;
  v: string | null;
}

export interface AwardsFtsData {
  block: Uint8Array | null;
  id: Generated<number | null>;
}

export interface AwardsFtsDocsize {
  id: Generated<number | null>;
  sz: Uint8Array | null;
}

export interface AwardsFtsIdx {
  pgno: string | null;
  segid: string;
  term: string;
}

export interface Badges {
  color_theme: Generated<string | null>;
  created_at: Generated<string | null>;
  description: string | null;
  icon: Generated<string | null>;
  id: string | null;
  name: string;
}

export interface Comments {
  content: string;
  created_at: Generated<string | null>;
  id: string | null;
  is_deleted: Generated<number | null>;
  target_id: string;
  target_type: string;
  updated_at: Generated<string | null>;
  user_id: string;
  zulip_message_id: string | null;
}

export interface D1Migrations {
  applied_at: Generated<string>;
  id: Generated<number | null>;
  name: string | null;
}

export interface DietaryCategories {
  category: string;
  restriction: string | null;
}

export interface Docs {
  category: string;
  cf_email: string | null;
  content: string;
  content_draft: string | null;
  description: string | null;
  is_deleted: Generated<number | null>;
  is_executive_summary: Generated<number | null>;
  is_portfolio: Generated<number | null>;
  revision_of: string | null;
  slug: string | null;
  sort_order: Generated<number | null>;
  status: Generated<string | null>;
  title: string;
  updated_at: Generated<string | null>;
}

export interface DocsFeedback {
  comment: string | null;
  created_at: Generated<string | null>;
  id: Generated<number | null>;
  is_helpful: number | null;
  slug: string;
}

export interface DocsFts {
  category: string | null;
  content: string | null;
  description: string | null;
  is_deleted: string | null;
  slug: string | null;
  status: string | null;
  title: string | null;
}

export interface DocsFtsConfig {
  k: string;
  v: string | null;
}

export interface DocsFtsContent {
  c0: string | null;
  c1: string | null;
  c2: string | null;
  c3: string | null;
  c4: string | null;
  c5: string | null;
  c6: string | null;
  id: Generated<number | null>;
}

export interface DocsFtsData {
  block: Uint8Array | null;
  id: Generated<number | null>;
}

export interface DocsFtsDocsize {
  id: Generated<number | null>;
  sz: Uint8Array | null;
}

export interface DocsFtsIdx {
  pgno: string | null;
  segid: string;
  term: string;
}

export interface DocsHistory {
  author_email: string | null;
  category: string | null;
  content: string | null;
  created_at: Generated<string | null>;
  description: string | null;
  id: Generated<number | null>;
  slug: string;
  title: string | null;
}

export interface DocumentContributors {
  id: Generated<number | null>;
  last_contributed_at: Generated<string | null>;
  room_id: string;
  user_avatar: string | null;
  user_id: string;
  user_name: string;
}

export interface DocumentHistory {
  content: string;
  created_at: Generated<string | null>;
  created_by: string | null;
  id: Generated<number | null>;
  room_id: string;
}

export interface EntityLinks {
  created_at: Generated<string | null>;
  id: string | null;
  link_type: Generated<string | null>;
  source_id: string;
  source_type: string;
  target_id: string;
  target_type: string;
}

export interface Events {
  category: Generated<string | null>;
  cf_email: string | null;
  content_draft: string | null;
  cover_image: string | null;
  date_end: string | null;
  date_start: string;
  description: string | null;
  gcal_event_id: string | null;
  id: string | null;
  is_deleted: Generated<number | null>;
  is_potluck: Generated<number | null>;
  is_volunteer: Generated<number | null>;
  location: string | null;
  meeting_notes: string | null;
  published_at: string | null;
  revision_of: string | null;
  season_id: number | null;
  status: Generated<string | null>;
  tba_event_key: string | null;
  title: string;
}

export interface EventsFts {
  description: string | null;
  id: string | null;
  is_deleted: string | null;
  location: string | null;
  status: string | null;
  title: string | null;
}

export interface EventsFtsConfig {
  k: string;
  v: string | null;
}

export interface EventsFtsContent {
  c0: string | null;
  c1: string | null;
  c2: string | null;
  c3: string | null;
  c4: string | null;
  c5: string | null;
  id: Generated<number | null>;
}

export interface EventsFtsData {
  block: Uint8Array | null;
  id: Generated<number | null>;
}

export interface EventsFtsDocsize {
  id: Generated<number | null>;
  sz: Uint8Array | null;
}

export interface EventsFtsIdx {
  pgno: string | null;
  segid: string;
  term: string;
}

export interface EventSignups {
  attended: Generated<number | null>;
  bringing: string | null;
  created_at: Generated<string | null>;
  event_id: string;
  id: Generated<number | null>;
  notes: string | null;
  prep_hours: Generated<number | null>;
  user_id: string;
}

export interface FinanceTransactions {
  amount: number;
  category: string;
  created_at: Generated<string | null>;
  date: string;
  description: string | null;
  id: string | null;
  logged_by: string | null;
  receipt_url: string | null;
  season_id: number | null;
  type: string;
}

export interface Inquiries {
  created_at: Generated<string | null>;
  email: string;
  id: string | null;
  metadata: string | null;
  name: string;
  status: Generated<string | null>;
  type: string;
}

export interface JudgeAccessCodes {
  code: string;
  created_at: Generated<string | null>;
  expires_at: string | null;
  id: string | null;
  label: Generated<string | null>;
}

export interface Locations {
  address: string | null;
  id: string | null;
  is_deleted: Generated<number | null>;
  maps_url: string | null;
  name: string;
}

export interface MatchStrategy {
  created_at: Generated<string | null>;
  event_id: string;
  id: string | null;
  match_number: number;
  our_role: string | null;
  partner_team: string | null;
  post_match_result: string | null;
  strategy_notes: string | null;
}

export interface MediaTags {
  folder: Generated<string | null>;
  key: string | null;
  tags: string | null;
}

export interface Notifications {
  created_at: Generated<string | null>;
  id: string | null;
  is_read: Generated<number | null>;
  link: string | null;
  message: string;
  priority: Generated<string | null>;
  title: string;
  user_id: string;
}

export interface OutreachFts {
  impact_summary: string | null;
  location: string | null;
  title: string | null;
}

export interface OutreachFtsConfig {
  k: string;
  v: string | null;
}

export interface OutreachFtsData {
  block: Uint8Array | null;
  id: Generated<number | null>;
}

export interface OutreachFtsDocsize {
  id: Generated<number | null>;
  sz: Uint8Array | null;
}

export interface OutreachFtsIdx {
  pgno: string | null;
  segid: string;
  term: string;
}

export interface OutreachLogs {
  cf_email: string | null;
  core_values: string | null;
  created_at: Generated<string | null>;
  date: string;
  hours: number | null;
  id: Generated<number | null>;
  impact_summary: string | null;
  is_deleted: Generated<number | null>;
  is_mentoring: Generated<number | null>;
  location: string | null;
  mentored_team_number: string | null;
  metadata: string | null;
  people_reached: number | null;
  season_id: number | null;
  students_count: Generated<number | null>;
  title: string;
}

export interface PageAnalytics {
  category: Generated<string | null>;
  id: Generated<number | null>;
  path: string;
  referrer: string | null;
  timestamp: Generated<string | null>;
  user_agent: string | null;
}

export interface PitScouting {
  can_help_with: string | null;
  created_at: Generated<string | null>;
  drive_train: string | null;
  event_id: string;
  id: string | null;
  image_url: string | null;
  needs_help_with: string | null;
  notes: string | null;
  scoring_capabilities: string | null;
  scouted_by: string | null;
  team_name: string | null;
  team_number: string;
  updated_at: Generated<string | null>;
}

export interface Posts {
  ast: string;
  author: string | null;
  cf_email: string | null;
  content_draft: string | null;
  date: string | null;
  is_deleted: Generated<number | null>;
  is_portfolio: Generated<number | null>;
  published_at: string | null;
  revision_of: string | null;
  season_id: number | null;
  slug: string | null;
  snippet: string | null;
  status: Generated<string | null>;
  thumbnail: string | null;
  title: string;
}

export interface PostsFts {
  ast: string | null;
  author: string | null;
  slug: string | null;
  snippet: string | null;
  title: string | null;
}

export interface PostsFtsConfig {
  k: string;
  v: string | null;
}

export interface PostsFtsContent {
  c0: string | null;
  c1: string | null;
  c2: string | null;
  c3: string | null;
  c4: string | null;
  id: Generated<number | null>;
}

export interface PostsFtsData {
  block: Uint8Array | null;
  id: Generated<number | null>;
}

export interface PostsFtsDocsize {
  id: Generated<number | null>;
  sz: Uint8Array | null;
}

export interface PostsFtsIdx {
  pgno: string | null;
  segid: string;
  term: string;
}

export interface PostsHistory {
  ast: string;
  author: string | null;
  author_email: string | null;
  created_at: Generated<string | null>;
  id: Generated<number | null>;
  season_id: number | null;
  slug: string;
  snippet: string | null;
  thumbnail: string | null;
  title: string;
}

export interface RateLimits {
  count: number;
  expires_at: number;
  ip: string | null;
}

export interface SeasonGoals {
  category: string;
  created_at: Generated<string | null>;
  current_value: Generated<number | null>;
  id: string | null;
  notes: string | null;
  season_id: number;
  target_value: number;
  updated_at: Generated<string | null>;
}

export interface Seasons {
  album_cover: string | null;
  album_url: string | null;
  challenge_name: string;
  created_at: Generated<string | null>;
  end_year: number | null;
  is_deleted: Generated<number | null>;
  robot_cad_url: string | null;
  robot_description: string | null;
  robot_image: string | null;
  robot_name: string | null;
  start_year: Generated<number | null>;
  status: Generated<string | null>;
  summary: string | null;
  updated_at: Generated<string | null>;
}

export interface Session {
  createdAt: number;
  expiresAt: number;
  id: string | null;
  ipAddress: string | null;
  token: string;
  updatedAt: number;
  userAgent: string | null;
  userId: string;
}

export interface Settings {
  key: string | null;
  updated_at: Generated<string | null>;
  value: string;
}

export interface SponsorMetrics {
  clicks: Generated<number | null>;
  created_at: Generated<string | null>;
  id: string | null;
  impressions: Generated<number | null>;
  sponsor_id: string;
  year_month: string;
}

export interface Sponsors {
  created_at: Generated<string | null>;
  id: string | null;
  is_active: Generated<number | null>;
  logo_url: string | null;
  name: string;
  tier: string;
  website_url: string | null;
}

export interface SponsorshipAssignments {
  sponsorship_id: string;
  user_id: string;
}

export interface SponsorshipPipeline {
  company_name: string;
  contact_person: string | null;
  created_at: Generated<string | null>;
  estimated_value: Generated<number | null>;
  id: string | null;
  notes: string | null;
  season_id: number | null;
  sponsor_id: string | null;
  status: Generated<string>;
  updated_at: Generated<string | null>;
  zulip_message_id: string | null;
}

export interface SponsorTokens {
  created_at: Generated<string | null>;
  created_by: string | null;
  sponsor_id: string;
  token: string | null;
}

export interface TaskAssignments {
  task_id: string;
  user_id: string;
}

export interface Tasks {
  assigned_to: string | null;
  created_at: Generated<string | null>;
  created_by: string;
  description: string | null;
  due_date: string | null;
  id: string | null;
  priority: Generated<string | null>;
  sort_order: Generated<number | null>;
  status: Generated<string | null>;
  title: string;
  updated_at: Generated<string | null>;
}

export interface User {
  createdAt: number;
  email: string;
  emailVerified: number;
  id: string | null;
  image: string | null;
  name: string;
  role: Generated<string | null>;
  twoFactorBackupCodes: string | null;
  twoFactorEnabled: Generated<number | null>;
  twoFactorSecret: string | null;
  updatedAt: number;
}

export interface UserBadges {
  awarded_at: Generated<string | null>;
  awarded_by: string | null;
  badge_id: string;
  id: Generated<number | null>;
  user_id: string;
}

export interface UserProfiles {
  bio: string | null;
  colleges: Generated<string | null>;
  contact_email: string | null;
  dietary_restrictions: string | null;
  emergency_contact_name: string | null;
  emergency_contact_phone: string | null;
  employers: Generated<string | null>;
  favorite_first_thing: string | null;
  favorite_food: string | null;
  favorite_robot_mechanism: string | null;
  first_name: string | null;
  fun_fact: string | null;
  grade_year: string | null;
  last_name: string | null;
  leadership_role: string | null;
  member_type: Generated<string | null>;
  nickname: string | null;
  parents_email: string | null;
  parents_name: string | null;
  phone: string | null;
  pre_match_superstition: string | null;
  pronouns: string | null;
  rookie_year: string | null;
  show_email: Generated<number | null>;
  show_on_about: Generated<number | null>;
  show_phone: Generated<number | null>;
  students_email: string | null;
  students_name: string | null;
  subteams: Generated<string | null>;
  tshirt_size: string | null;
  updated_at: Generated<string | null>;
  user_id: string | null;
}

export interface UserProfilesFts {
  bio: string | null;
  first_name: string | null;
  last_name: string | null;
  nickname: string | null;
  show_on_about: string | null;
  user_id: string | null;
}

export interface UserProfilesFtsConfig {
  k: string;
  v: string | null;
}

export interface UserProfilesFtsContent {
  c0: string | null;
  c1: string | null;
  c2: string | null;
  c3: string | null;
  c4: string | null;
  c5: string | null;
  id: Generated<number | null>;
}

export interface UserProfilesFtsData {
  block: Uint8Array | null;
  id: Generated<number | null>;
}

export interface UserProfilesFtsDocsize {
  id: Generated<number | null>;
  sz: Uint8Array | null;
}

export interface UserProfilesFtsIdx {
  pgno: string | null;
  segid: string;
  term: string;
}

export interface Verification {
  createdAt: number | null;
  expiresAt: number;
  id: string | null;
  identifier: string;
  updatedAt: number | null;
  value: string;
}

export interface DB {
  _cf_METADATA: _CfMETADATA;
  account: Account;
  audit_log: AuditLog;
  awards: Awards;
  awards_fts: AwardsFts;
  awards_fts_config: AwardsFtsConfig;
  awards_fts_data: AwardsFtsData;
  awards_fts_docsize: AwardsFtsDocsize;
  awards_fts_idx: AwardsFtsIdx;
  badges: Badges;
  comments: Comments;
  d1_migrations: D1Migrations;
  dietary_categories: DietaryCategories;
  docs: Docs;
  docs_feedback: DocsFeedback;
  docs_fts: DocsFts;
  docs_fts_config: DocsFtsConfig;
  docs_fts_content: DocsFtsContent;
  docs_fts_data: DocsFtsData;
  docs_fts_docsize: DocsFtsDocsize;
  docs_fts_idx: DocsFtsIdx;
  docs_history: DocsHistory;
  document_contributors: DocumentContributors;
  document_history: DocumentHistory;
  entity_links: EntityLinks;
  event_signups: EventSignups;
  events: Events;
  events_fts: EventsFts;
  events_fts_config: EventsFtsConfig;
  events_fts_content: EventsFtsContent;
  events_fts_data: EventsFtsData;
  events_fts_docsize: EventsFtsDocsize;
  events_fts_idx: EventsFtsIdx;
  finance_transactions: FinanceTransactions;
  inquiries: Inquiries;
  judge_access_codes: JudgeAccessCodes;
  locations: Locations;
  match_strategy: MatchStrategy;
  media_tags: MediaTags;
  notifications: Notifications;
  outreach_fts: OutreachFts;
  outreach_fts_config: OutreachFtsConfig;
  outreach_fts_data: OutreachFtsData;
  outreach_fts_docsize: OutreachFtsDocsize;
  outreach_fts_idx: OutreachFtsIdx;
  outreach_logs: OutreachLogs;
  page_analytics: PageAnalytics;
  pit_scouting: PitScouting;
  posts: Posts;
  posts_fts: PostsFts;
  posts_fts_config: PostsFtsConfig;
  posts_fts_content: PostsFtsContent;
  posts_fts_data: PostsFtsData;
  posts_fts_docsize: PostsFtsDocsize;
  posts_fts_idx: PostsFtsIdx;
  posts_history: PostsHistory;
  rate_limits: RateLimits;
  season_goals: SeasonGoals;
  seasons: Seasons;
  session: Session;
  settings: Settings;
  sponsor_metrics: SponsorMetrics;
  sponsor_tokens: SponsorTokens;
  sponsors: Sponsors;
  sponsorship_assignments: SponsorshipAssignments;
  sponsorship_pipeline: SponsorshipPipeline;
  task_assignments: TaskAssignments;
  tasks: Tasks;
  user: User;
  user_badges: UserBadges;
  user_profiles: UserProfiles;
  user_profiles_fts: UserProfilesFts;
  user_profiles_fts_config: UserProfilesFtsConfig;
  user_profiles_fts_content: UserProfilesFtsContent;
  user_profiles_fts_data: UserProfilesFtsData;
  user_profiles_fts_docsize: UserProfilesFtsDocsize;
  user_profiles_fts_idx: UserProfilesFtsIdx;
  verification: Verification;
}
