import { useState } from "react";
import { motion } from "framer-motion";

interface ResponsiveImageProps {
  src: string;
  alt: string;
  className?: string;
  imgClassName?: string;
  fetchPriority?: "high" | "low" | "auto";  // W4C-IMG-01: fetch priority hint
  decoding?: "sync" | "async" | "auto";     // W4C-IMG-01: decoding hint
}

export default function ResponsiveImage({ src, alt, className = "", imgClassName = "", fetchPriority = "auto", decoding = "async" }: ResponsiveImageProps) {
  const [isLoaded, setIsLoaded] = useState(false);
  const [isError, setIsError] = useState(false);

  const fallbackSrc = "/news_1.png"; 

  // Generate srcset for the image based on sizes generated by the build script
  // Example sizes: 320, 640, 1024, 1920
  const baseSrc = src.replace(/\.(png|jpg|jpeg)$/i, '');
  const isWebp = src.endsWith('.webp');

  const srcSet = !isWebp && !isError
    ? `${baseSrc}-320w.webp 320w, ${baseSrc}-640w.webp 640w, ${baseSrc}-1024w.webp 1024w, ${baseSrc}-1920w.webp 1920w`
    : undefined;

  return (
    <div className={`relative overflow-hidden bg-white/5 ${className}`}>
      {/* Skeleton Placeholder */}
      <motion.div
        initial={{ opacity: 1 }}
        animate={{ opacity: (isLoaded || isError) ? 0 : 1 }}
        transition={{ duration: 0.5 }}
        className="absolute inset-0 bg-marble/5 animate-pulse backdrop-blur-xl z-0"
      />

      <picture className={`w-full h-full absolute inset-0 z-10 ${imgClassName}`}>
        {!isError && <source srcSet={srcSet || `${baseSrc}.webp`} type="image/webp" sizes="(max-width: 640px) 320px, (max-width: 1024px) 640px, (max-width: 1920px) 1024px, 1920px" />}
        <motion.img
          src={isError ? fallbackSrc : src}
          alt={alt}
          initial={{ opacity: 0, filter: "blur(10px)", scale: 1.05 }}
          animate={{ opacity: (isLoaded || isError) ? 1 : 0, filter: (isLoaded || isError) ? "blur(0px)" : "blur(10px)", scale: (isLoaded || isError) ? 1 : 1.05 }}
          transition={{ duration: 0.8, ease: "easeOut" }}
          loading="lazy"
          fetchPriority={fetchPriority}
          decoding={decoding}
          onLoad={() => setIsLoaded(true)}
          onError={() => {
            if (!isError) setIsError(true);
          }}
          className="w-full h-full object-cover"
        />
      </picture>
    </div>
  );
}
