-- Clean up Playwright E2E data from the production database
-- This script safely removes artifacts generated by E2E testing

-- 1. Clean up tasks
DELETE FROM tasks WHERE title LIKE '%Playwright%';
DELETE FROM tasks WHERE title LIKE '%E2E Test%';

-- 2. Clean up mock users if any
DELETE FROM user WHERE name LIKE '%Playwright%';
DELETE FROM user WHERE email LIKE '%@example.com%';

-- 3. Clean up other potential test artifacts
DELETE FROM docs WHERE title LIKE '%Playwright%';
DELETE FROM posts WHERE title LIKE '%Playwright%';

-- 4. Clean up sponsorships created during testing
DELETE FROM sponsors WHERE name LIKE '%Playwright%';

-- Note: CASCADE DELETE in SQLite will automatically handle associated child records
-- (e.g., task_assignments for deleted tasks, or user_sessions for deleted users)
