/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TechStackRouteImport } from './routes/tech-stack'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SimRunnerRouteImport } from './routes/sim-runner'
import { Route as SeasonsRouteImport } from './routes/seasons'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as JoinRouteImport } from './routes/join'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BugReportRouteImport } from './routes/bug-report'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideosIndexRouteImport } from './routes/videos/index'
import { Route as SponsorsIndexRouteImport } from './routes/sponsors/index'
import { Route as OnshapeIndexRouteImport } from './routes/onshape/index'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as JudgesIndexRouteImport } from './routes/judges/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AlbumsIndexRouteImport } from './routes/albums/index'
import { Route as AcademyIndexRouteImport } from './routes/academy/index'
import { Route as VideosIdRouteImport } from './routes/videos/$id'
import { Route as ProfileUserIdRouteImport } from './routes/profile/$userId'
import { Route as OnshapeBomHistoryRouteImport } from './routes/onshape/bom-history'
import { Route as LocationsMorgantownRouteImport } from './routes/locations/morgantown'
import { Route as JudgesPrintRouteImport } from './routes/judges/print'
import { Route as EventsIdRouteImport } from './routes/events/$id'
import { Route as DocsSlugRouteImport } from './routes/docs/$slug'
import { Route as DevelopersApiRouteImport } from './routes/developers/api'
import { Route as DashboardYoutubeRouteImport } from './routes/dashboard/youtube'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardStore_ordersRouteImport } from './routes/dashboard/store_orders'
import { Route as DashboardSponsorsRouteImport } from './routes/dashboard/sponsors'
import { Route as DashboardSponsor_tokensRouteImport } from './routes/dashboard/sponsor_tokens'
import { Route as DashboardSocialRouteImport } from './routes/dashboard/social'
import { Route as DashboardSimulationsRouteImport } from './routes/dashboard/simulations'
import { Route as DashboardSimsRouteImport } from './routes/dashboard/sims'
import { Route as DashboardScoutingRouteImport } from './routes/dashboard/scouting'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardPhotosRouteImport } from './routes/dashboard/photos'
import { Route as DashboardOutreachRouteImport } from './routes/dashboard/outreach'
import { Route as DashboardMass_emailRouteImport } from './routes/dashboard/mass_email'
import { Route as DashboardManage_seasonsRouteImport } from './routes/dashboard/manage_seasons'
import { Route as DashboardManage_eventRouteImport } from './routes/dashboard/manage_event'
import { Route as DashboardManage_docsRouteImport } from './routes/dashboard/manage_docs'
import { Route as DashboardManage_blogRouteImport } from './routes/dashboard/manage_blog'
import { Route as DashboardManage_albumsRouteImport } from './routes/dashboard/manage_albums'
import { Route as DashboardLogisticsRouteImport } from './routes/dashboard/logistics'
import { Route as DashboardLocationsRouteImport } from './routes/dashboard/locations'
import { Route as DashboardLegacyRouteImport } from './routes/dashboard/legacy'
import { Route as DashboardJudge_codesRouteImport } from './routes/dashboard/judge_codes'
import { Route as DashboardIntegrationsRouteImport } from './routes/dashboard/integrations'
import { Route as DashboardInquiriesRouteImport } from './routes/dashboard/inquiries'
import { Route as DashboardImpact_rosterRouteImport } from './routes/dashboard/impact_roster'
import { Route as DashboardGmailRouteImport } from './routes/dashboard/gmail'
import { Route as DashboardFinanceRouteImport } from './routes/dashboard/finance'
import { Route as DashboardFilesRouteImport } from './routes/dashboard/files'
import { Route as DashboardDriveDocsRouteImport } from './routes/dashboard/drive-docs'
import { Route as DashboardDb_studioRouteImport } from './routes/dashboard/db_studio'
import { Route as DashboardCommand_centerRouteImport } from './routes/dashboard/command_center'
import { Route as DashboardBadgesRouteImport } from './routes/dashboard/badges'
import { Route as DashboardAssetsRouteImport } from './routes/dashboard/assets'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AlbumsIdRouteImport } from './routes/albums/$id'
import { Route as AcademySlugRouteImport } from './routes/academy/$slug'
import { Route as DashboardTasksIndexRouteImport } from './routes/dashboard/tasks/index'
import { Route as DashboardSeasonsIndexRouteImport } from './routes/dashboard/seasons/index'
import { Route as DashboardEventIndexRouteImport } from './routes/dashboard/event/index'
import { Route as DashboardDocsIndexRouteImport } from './routes/dashboard/docs/index'
import { Route as DashboardBlogIndexRouteImport } from './routes/dashboard/blog/index'
import { Route as SponsorsRoiTokenIdRouteImport } from './routes/sponsors/roi/$tokenId'
import { Route as DashboardTasksTaskIdRouteImport } from './routes/dashboard/tasks/$taskId'
import { Route as DashboardSeasonsEditIdRouteImport } from './routes/dashboard/seasons/$editId'
import { Route as DashboardManage_albumsIdRouteImport } from './routes/dashboard/manage_albums.$id'
import { Route as DashboardEventEditIdRouteImport } from './routes/dashboard/event/$editId'
import { Route as DashboardDocsEditSlugRouteImport } from './routes/dashboard/docs/$editSlug'
import { Route as DashboardBlogEditSlugRouteImport } from './routes/dashboard/blog/$editSlug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TechStackRoute = TechStackRouteImport.update({
  id: '/tech-stack',
  path: '/tech-stack',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SimRunnerRoute = SimRunnerRouteImport.update({
  id: '/sim-runner',
  path: '/sim-runner',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsRoute = SeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BugReportRoute = BugReportRouteImport.update({
  id: '/bug-report',
  path: '/bug-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsIndexRoute = SponsorsIndexRouteImport.update({
  id: '/sponsors/',
  path: '/sponsors/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnshapeIndexRoute = OnshapeIndexRouteImport.update({
  id: '/onshape/',
  path: '/onshape/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgesIndexRoute = JudgesIndexRouteImport.update({
  id: '/judges/',
  path: '/judges/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsIndexRoute = AlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/academy/',
  path: '/academy/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIdRoute = VideosIdRouteImport.update({
  id: '/videos/$id',
  path: '/videos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const OnshapeBomHistoryRoute = OnshapeBomHistoryRouteImport.update({
  id: '/onshape/bom-history',
  path: '/onshape/bom-history',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsMorgantownRoute = LocationsMorgantownRouteImport.update({
  id: '/locations/morgantown',
  path: '/locations/morgantown',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgesPrintRoute = JudgesPrintRouteImport.update({
  id: '/judges/print',
  path: '/judges/print',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersApiRoute = DevelopersApiRouteImport.update({
  id: '/developers/api',
  path: '/developers/api',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardYoutubeRoute = DashboardYoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStore_ordersRoute = DashboardStore_ordersRouteImport.update({
  id: '/store_orders',
  path: '/store_orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSponsorsRoute = DashboardSponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSponsor_tokensRoute = DashboardSponsor_tokensRouteImport.update({
  id: '/sponsor_tokens',
  path: '/sponsor_tokens',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSocialRoute = DashboardSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSimulationsRoute = DashboardSimulationsRouteImport.update({
  id: '/simulations',
  path: '/simulations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSimsRoute = DashboardSimsRouteImport.update({
  id: '/sims',
  path: '/sims',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardScoutingRoute = DashboardScoutingRouteImport.update({
  id: '/scouting',
  path: '/scouting',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPhotosRoute = DashboardPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOutreachRoute = DashboardOutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMass_emailRoute = DashboardMass_emailRouteImport.update({
  id: '/mass_email',
  path: '/mass_email',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardManage_seasonsRoute = DashboardManage_seasonsRouteImport.update({
  id: '/manage_seasons',
  path: '/manage_seasons',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardManage_eventRoute = DashboardManage_eventRouteImport.update({
  id: '/manage_event',
  path: '/manage_event',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardManage_docsRoute = DashboardManage_docsRouteImport.update({
  id: '/manage_docs',
  path: '/manage_docs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardManage_blogRoute = DashboardManage_blogRouteImport.update({
  id: '/manage_blog',
  path: '/manage_blog',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardManage_albumsRoute = DashboardManage_albumsRouteImport.update({
  id: '/manage_albums',
  path: '/manage_albums',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogisticsRoute = DashboardLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLocationsRoute = DashboardLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLegacyRoute = DashboardLegacyRouteImport.update({
  id: '/legacy',
  path: '/legacy',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJudge_codesRoute = DashboardJudge_codesRouteImport.update({
  id: '/judge_codes',
  path: '/judge_codes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntegrationsRoute = DashboardIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInquiriesRoute = DashboardInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImpact_rosterRoute = DashboardImpact_rosterRouteImport.update({
  id: '/impact_roster',
  path: '/impact_roster',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGmailRoute = DashboardGmailRouteImport.update({
  id: '/gmail',
  path: '/gmail',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFinanceRoute = DashboardFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFilesRoute = DashboardFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDriveDocsRoute = DashboardDriveDocsRouteImport.update({
  id: '/drive-docs',
  path: '/drive-docs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDb_studioRoute = DashboardDb_studioRouteImport.update({
  id: '/db_studio',
  path: '/db_studio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommand_centerRoute = DashboardCommand_centerRouteImport.update({
  id: '/command_center',
  path: '/command_center',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBadgesRoute = DashboardBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssetsRoute = DashboardAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsIdRoute = AlbumsIdRouteImport.update({
  id: '/albums/$id',
  path: '/albums/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademySlugRoute = AcademySlugRouteImport.update({
  id: '/academy/$slug',
  path: '/academy/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTasksIndexRoute = DashboardTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSeasonsIndexRoute = DashboardSeasonsIndexRouteImport.update({
  id: '/seasons/',
  path: '/seasons/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventIndexRoute = DashboardEventIndexRouteImport.update({
  id: '/event/',
  path: '/event/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocsIndexRoute = DashboardDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBlogIndexRoute = DashboardBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => DashboardRoute,
} as any)
const SponsorsRoiTokenIdRoute = SponsorsRoiTokenIdRouteImport.update({
  id: '/sponsors/roi/$tokenId',
  path: '/sponsors/roi/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTasksTaskIdRoute = DashboardTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSeasonsEditIdRoute = DashboardSeasonsEditIdRouteImport.update({
  id: '/seasons/$editId',
  path: '/seasons/$editId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardManage_albumsIdRoute =
  DashboardManage_albumsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => DashboardManage_albumsRoute,
  } as any)
const DashboardEventEditIdRoute = DashboardEventEditIdRouteImport.update({
  id: '/event/$editId',
  path: '/event/$editId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocsEditSlugRoute = DashboardDocsEditSlugRouteImport.update({
  id: '/docs/$editSlug',
  path: '/docs/$editSlug',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBlogEditSlugRoute = DashboardBlogEditSlugRouteImport.update({
  id: '/blog/$editSlug',
  path: '/blog/$editSlug',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/bug-report': typeof BugReportRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/outreach': typeof OutreachRoute
  '/privacy': typeof PrivacyRoute
  '/seasons': typeof SeasonsRoute
  '/sim-runner': typeof SimRunnerRoute
  '/store': typeof StoreRoute
  '/tech-stack': typeof TechStackRoute
  '/terms': typeof TermsRoute
  '/academy/$slug': typeof AcademySlugRoute
  '/albums/$id': typeof AlbumsIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/assets': typeof DashboardAssetsRoute
  '/dashboard/badges': typeof DashboardBadgesRoute
  '/dashboard/command_center': typeof DashboardCommand_centerRoute
  '/dashboard/db_studio': typeof DashboardDb_studioRoute
  '/dashboard/drive-docs': typeof DashboardDriveDocsRoute
  '/dashboard/files': typeof DashboardFilesRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/gmail': typeof DashboardGmailRoute
  '/dashboard/impact_roster': typeof DashboardImpact_rosterRoute
  '/dashboard/inquiries': typeof DashboardInquiriesRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/judge_codes': typeof DashboardJudge_codesRoute
  '/dashboard/legacy': typeof DashboardLegacyRoute
  '/dashboard/locations': typeof DashboardLocationsRoute
  '/dashboard/logistics': typeof DashboardLogisticsRoute
  '/dashboard/manage_albums': typeof DashboardManage_albumsRouteWithChildren
  '/dashboard/manage_blog': typeof DashboardManage_blogRoute
  '/dashboard/manage_docs': typeof DashboardManage_docsRoute
  '/dashboard/manage_event': typeof DashboardManage_eventRoute
  '/dashboard/manage_seasons': typeof DashboardManage_seasonsRoute
  '/dashboard/mass_email': typeof DashboardMass_emailRoute
  '/dashboard/outreach': typeof DashboardOutreachRoute
  '/dashboard/photos': typeof DashboardPhotosRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/scouting': typeof DashboardScoutingRoute
  '/dashboard/sims': typeof DashboardSimsRoute
  '/dashboard/simulations': typeof DashboardSimulationsRoute
  '/dashboard/social': typeof DashboardSocialRoute
  '/dashboard/sponsor_tokens': typeof DashboardSponsor_tokensRoute
  '/dashboard/sponsors': typeof DashboardSponsorsRoute
  '/dashboard/store_orders': typeof DashboardStore_ordersRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/youtube': typeof DashboardYoutubeRoute
  '/developers/api': typeof DevelopersApiRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/events/$id': typeof EventsIdRoute
  '/judges/print': typeof JudgesPrintRoute
  '/locations/morgantown': typeof LocationsMorgantownRoute
  '/onshape/bom-history': typeof OnshapeBomHistoryRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/videos/$id': typeof VideosIdRoute
  '/academy/': typeof AcademyIndexRoute
  '/albums/': typeof AlbumsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/judges/': typeof JudgesIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/onshape/': typeof OnshapeIndexRoute
  '/sponsors/': typeof SponsorsIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/dashboard/blog/$editSlug': typeof DashboardBlogEditSlugRoute
  '/dashboard/docs/$editSlug': typeof DashboardDocsEditSlugRoute
  '/dashboard/event/$editId': typeof DashboardEventEditIdRoute
  '/dashboard/manage_albums/$id': typeof DashboardManage_albumsIdRoute
  '/dashboard/seasons/$editId': typeof DashboardSeasonsEditIdRoute
  '/dashboard/tasks/$taskId': typeof DashboardTasksTaskIdRoute
  '/sponsors/roi/$tokenId': typeof SponsorsRoiTokenIdRoute
  '/dashboard/blog/': typeof DashboardBlogIndexRoute
  '/dashboard/docs/': typeof DashboardDocsIndexRoute
  '/dashboard/event/': typeof DashboardEventIndexRoute
  '/dashboard/seasons/': typeof DashboardSeasonsIndexRoute
  '/dashboard/tasks/': typeof DashboardTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/bug-report': typeof BugReportRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/outreach': typeof OutreachRoute
  '/privacy': typeof PrivacyRoute
  '/seasons': typeof SeasonsRoute
  '/sim-runner': typeof SimRunnerRoute
  '/store': typeof StoreRoute
  '/tech-stack': typeof TechStackRoute
  '/terms': typeof TermsRoute
  '/academy/$slug': typeof AcademySlugRoute
  '/albums/$id': typeof AlbumsIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/assets': typeof DashboardAssetsRoute
  '/dashboard/badges': typeof DashboardBadgesRoute
  '/dashboard/command_center': typeof DashboardCommand_centerRoute
  '/dashboard/db_studio': typeof DashboardDb_studioRoute
  '/dashboard/drive-docs': typeof DashboardDriveDocsRoute
  '/dashboard/files': typeof DashboardFilesRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/gmail': typeof DashboardGmailRoute
  '/dashboard/impact_roster': typeof DashboardImpact_rosterRoute
  '/dashboard/inquiries': typeof DashboardInquiriesRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/judge_codes': typeof DashboardJudge_codesRoute
  '/dashboard/legacy': typeof DashboardLegacyRoute
  '/dashboard/locations': typeof DashboardLocationsRoute
  '/dashboard/logistics': typeof DashboardLogisticsRoute
  '/dashboard/manage_albums': typeof DashboardManage_albumsRouteWithChildren
  '/dashboard/manage_blog': typeof DashboardManage_blogRoute
  '/dashboard/manage_docs': typeof DashboardManage_docsRoute
  '/dashboard/manage_event': typeof DashboardManage_eventRoute
  '/dashboard/manage_seasons': typeof DashboardManage_seasonsRoute
  '/dashboard/mass_email': typeof DashboardMass_emailRoute
  '/dashboard/outreach': typeof DashboardOutreachRoute
  '/dashboard/photos': typeof DashboardPhotosRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/scouting': typeof DashboardScoutingRoute
  '/dashboard/sims': typeof DashboardSimsRoute
  '/dashboard/simulations': typeof DashboardSimulationsRoute
  '/dashboard/social': typeof DashboardSocialRoute
  '/dashboard/sponsor_tokens': typeof DashboardSponsor_tokensRoute
  '/dashboard/sponsors': typeof DashboardSponsorsRoute
  '/dashboard/store_orders': typeof DashboardStore_ordersRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/youtube': typeof DashboardYoutubeRoute
  '/developers/api': typeof DevelopersApiRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/events/$id': typeof EventsIdRoute
  '/judges/print': typeof JudgesPrintRoute
  '/locations/morgantown': typeof LocationsMorgantownRoute
  '/onshape/bom-history': typeof OnshapeBomHistoryRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/videos/$id': typeof VideosIdRoute
  '/academy': typeof AcademyIndexRoute
  '/albums': typeof AlbumsIndexRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/docs': typeof DocsIndexRoute
  '/events': typeof EventsIndexRoute
  '/judges': typeof JudgesIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/onshape': typeof OnshapeIndexRoute
  '/sponsors': typeof SponsorsIndexRoute
  '/videos': typeof VideosIndexRoute
  '/dashboard/blog/$editSlug': typeof DashboardBlogEditSlugRoute
  '/dashboard/docs/$editSlug': typeof DashboardDocsEditSlugRoute
  '/dashboard/event/$editId': typeof DashboardEventEditIdRoute
  '/dashboard/manage_albums/$id': typeof DashboardManage_albumsIdRoute
  '/dashboard/seasons/$editId': typeof DashboardSeasonsEditIdRoute
  '/dashboard/tasks/$taskId': typeof DashboardTasksTaskIdRoute
  '/sponsors/roi/$tokenId': typeof SponsorsRoiTokenIdRoute
  '/dashboard/blog': typeof DashboardBlogIndexRoute
  '/dashboard/docs': typeof DashboardDocsIndexRoute
  '/dashboard/event': typeof DashboardEventIndexRoute
  '/dashboard/seasons': typeof DashboardSeasonsIndexRoute
  '/dashboard/tasks': typeof DashboardTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/bug-report': typeof BugReportRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/outreach': typeof OutreachRoute
  '/privacy': typeof PrivacyRoute
  '/seasons': typeof SeasonsRoute
  '/sim-runner': typeof SimRunnerRoute
  '/store': typeof StoreRoute
  '/tech-stack': typeof TechStackRoute
  '/terms': typeof TermsRoute
  '/academy/$slug': typeof AcademySlugRoute
  '/albums/$id': typeof AlbumsIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/assets': typeof DashboardAssetsRoute
  '/dashboard/badges': typeof DashboardBadgesRoute
  '/dashboard/command_center': typeof DashboardCommand_centerRoute
  '/dashboard/db_studio': typeof DashboardDb_studioRoute
  '/dashboard/drive-docs': typeof DashboardDriveDocsRoute
  '/dashboard/files': typeof DashboardFilesRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/gmail': typeof DashboardGmailRoute
  '/dashboard/impact_roster': typeof DashboardImpact_rosterRoute
  '/dashboard/inquiries': typeof DashboardInquiriesRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/judge_codes': typeof DashboardJudge_codesRoute
  '/dashboard/legacy': typeof DashboardLegacyRoute
  '/dashboard/locations': typeof DashboardLocationsRoute
  '/dashboard/logistics': typeof DashboardLogisticsRoute
  '/dashboard/manage_albums': typeof DashboardManage_albumsRouteWithChildren
  '/dashboard/manage_blog': typeof DashboardManage_blogRoute
  '/dashboard/manage_docs': typeof DashboardManage_docsRoute
  '/dashboard/manage_event': typeof DashboardManage_eventRoute
  '/dashboard/manage_seasons': typeof DashboardManage_seasonsRoute
  '/dashboard/mass_email': typeof DashboardMass_emailRoute
  '/dashboard/outreach': typeof DashboardOutreachRoute
  '/dashboard/photos': typeof DashboardPhotosRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/scouting': typeof DashboardScoutingRoute
  '/dashboard/sims': typeof DashboardSimsRoute
  '/dashboard/simulations': typeof DashboardSimulationsRoute
  '/dashboard/social': typeof DashboardSocialRoute
  '/dashboard/sponsor_tokens': typeof DashboardSponsor_tokensRoute
  '/dashboard/sponsors': typeof DashboardSponsorsRoute
  '/dashboard/store_orders': typeof DashboardStore_ordersRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/youtube': typeof DashboardYoutubeRoute
  '/developers/api': typeof DevelopersApiRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/events/$id': typeof EventsIdRoute
  '/judges/print': typeof JudgesPrintRoute
  '/locations/morgantown': typeof LocationsMorgantownRoute
  '/onshape/bom-history': typeof OnshapeBomHistoryRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/videos/$id': typeof VideosIdRoute
  '/academy/': typeof AcademyIndexRoute
  '/albums/': typeof AlbumsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/judges/': typeof JudgesIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/onshape/': typeof OnshapeIndexRoute
  '/sponsors/': typeof SponsorsIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/dashboard/blog/$editSlug': typeof DashboardBlogEditSlugRoute
  '/dashboard/docs/$editSlug': typeof DashboardDocsEditSlugRoute
  '/dashboard/event/$editId': typeof DashboardEventEditIdRoute
  '/dashboard/manage_albums/$id': typeof DashboardManage_albumsIdRoute
  '/dashboard/seasons/$editId': typeof DashboardSeasonsEditIdRoute
  '/dashboard/tasks/$taskId': typeof DashboardTasksTaskIdRoute
  '/sponsors/roi/$tokenId': typeof SponsorsRoiTokenIdRoute
  '/dashboard/blog/': typeof DashboardBlogIndexRoute
  '/dashboard/docs/': typeof DashboardDocsIndexRoute
  '/dashboard/event/': typeof DashboardEventIndexRoute
  '/dashboard/seasons/': typeof DashboardSeasonsIndexRoute
  '/dashboard/tasks/': typeof DashboardTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/accessibility'
    | '/bug-report'
    | '/dashboard'
    | '/gallery'
    | '/join'
    | '/leaderboard'
    | '/login'
    | '/outreach'
    | '/privacy'
    | '/seasons'
    | '/sim-runner'
    | '/store'
    | '/tech-stack'
    | '/terms'
    | '/academy/$slug'
    | '/albums/$id'
    | '/blog/$slug'
    | '/dashboard/analytics'
    | '/dashboard/assets'
    | '/dashboard/badges'
    | '/dashboard/command_center'
    | '/dashboard/db_studio'
    | '/dashboard/drive-docs'
    | '/dashboard/files'
    | '/dashboard/finance'
    | '/dashboard/gmail'
    | '/dashboard/impact_roster'
    | '/dashboard/inquiries'
    | '/dashboard/integrations'
    | '/dashboard/judge_codes'
    | '/dashboard/legacy'
    | '/dashboard/locations'
    | '/dashboard/logistics'
    | '/dashboard/manage_albums'
    | '/dashboard/manage_blog'
    | '/dashboard/manage_docs'
    | '/dashboard/manage_event'
    | '/dashboard/manage_seasons'
    | '/dashboard/mass_email'
    | '/dashboard/outreach'
    | '/dashboard/photos'
    | '/dashboard/profile'
    | '/dashboard/scouting'
    | '/dashboard/sims'
    | '/dashboard/simulations'
    | '/dashboard/social'
    | '/dashboard/sponsor_tokens'
    | '/dashboard/sponsors'
    | '/dashboard/store_orders'
    | '/dashboard/users'
    | '/dashboard/youtube'
    | '/developers/api'
    | '/docs/$slug'
    | '/events/$id'
    | '/judges/print'
    | '/locations/morgantown'
    | '/onshape/bom-history'
    | '/profile/$userId'
    | '/videos/$id'
    | '/academy/'
    | '/albums/'
    | '/blog/'
    | '/dashboard/'
    | '/docs/'
    | '/events/'
    | '/judges/'
    | '/locations/'
    | '/onshape/'
    | '/sponsors/'
    | '/videos/'
    | '/dashboard/blog/$editSlug'
    | '/dashboard/docs/$editSlug'
    | '/dashboard/event/$editId'
    | '/dashboard/manage_albums/$id'
    | '/dashboard/seasons/$editId'
    | '/dashboard/tasks/$taskId'
    | '/sponsors/roi/$tokenId'
    | '/dashboard/blog/'
    | '/dashboard/docs/'
    | '/dashboard/event/'
    | '/dashboard/seasons/'
    | '/dashboard/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/accessibility'
    | '/bug-report'
    | '/gallery'
    | '/join'
    | '/leaderboard'
    | '/login'
    | '/outreach'
    | '/privacy'
    | '/seasons'
    | '/sim-runner'
    | '/store'
    | '/tech-stack'
    | '/terms'
    | '/academy/$slug'
    | '/albums/$id'
    | '/blog/$slug'
    | '/dashboard/analytics'
    | '/dashboard/assets'
    | '/dashboard/badges'
    | '/dashboard/command_center'
    | '/dashboard/db_studio'
    | '/dashboard/drive-docs'
    | '/dashboard/files'
    | '/dashboard/finance'
    | '/dashboard/gmail'
    | '/dashboard/impact_roster'
    | '/dashboard/inquiries'
    | '/dashboard/integrations'
    | '/dashboard/judge_codes'
    | '/dashboard/legacy'
    | '/dashboard/locations'
    | '/dashboard/logistics'
    | '/dashboard/manage_albums'
    | '/dashboard/manage_blog'
    | '/dashboard/manage_docs'
    | '/dashboard/manage_event'
    | '/dashboard/manage_seasons'
    | '/dashboard/mass_email'
    | '/dashboard/outreach'
    | '/dashboard/photos'
    | '/dashboard/profile'
    | '/dashboard/scouting'
    | '/dashboard/sims'
    | '/dashboard/simulations'
    | '/dashboard/social'
    | '/dashboard/sponsor_tokens'
    | '/dashboard/sponsors'
    | '/dashboard/store_orders'
    | '/dashboard/users'
    | '/dashboard/youtube'
    | '/developers/api'
    | '/docs/$slug'
    | '/events/$id'
    | '/judges/print'
    | '/locations/morgantown'
    | '/onshape/bom-history'
    | '/profile/$userId'
    | '/videos/$id'
    | '/academy'
    | '/albums'
    | '/blog'
    | '/dashboard'
    | '/docs'
    | '/events'
    | '/judges'
    | '/locations'
    | '/onshape'
    | '/sponsors'
    | '/videos'
    | '/dashboard/blog/$editSlug'
    | '/dashboard/docs/$editSlug'
    | '/dashboard/event/$editId'
    | '/dashboard/manage_albums/$id'
    | '/dashboard/seasons/$editId'
    | '/dashboard/tasks/$taskId'
    | '/sponsors/roi/$tokenId'
    | '/dashboard/blog'
    | '/dashboard/docs'
    | '/dashboard/event'
    | '/dashboard/seasons'
    | '/dashboard/tasks'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/accessibility'
    | '/bug-report'
    | '/dashboard'
    | '/gallery'
    | '/join'
    | '/leaderboard'
    | '/login'
    | '/outreach'
    | '/privacy'
    | '/seasons'
    | '/sim-runner'
    | '/store'
    | '/tech-stack'
    | '/terms'
    | '/academy/$slug'
    | '/albums/$id'
    | '/blog/$slug'
    | '/dashboard/analytics'
    | '/dashboard/assets'
    | '/dashboard/badges'
    | '/dashboard/command_center'
    | '/dashboard/db_studio'
    | '/dashboard/drive-docs'
    | '/dashboard/files'
    | '/dashboard/finance'
    | '/dashboard/gmail'
    | '/dashboard/impact_roster'
    | '/dashboard/inquiries'
    | '/dashboard/integrations'
    | '/dashboard/judge_codes'
    | '/dashboard/legacy'
    | '/dashboard/locations'
    | '/dashboard/logistics'
    | '/dashboard/manage_albums'
    | '/dashboard/manage_blog'
    | '/dashboard/manage_docs'
    | '/dashboard/manage_event'
    | '/dashboard/manage_seasons'
    | '/dashboard/mass_email'
    | '/dashboard/outreach'
    | '/dashboard/photos'
    | '/dashboard/profile'
    | '/dashboard/scouting'
    | '/dashboard/sims'
    | '/dashboard/simulations'
    | '/dashboard/social'
    | '/dashboard/sponsor_tokens'
    | '/dashboard/sponsors'
    | '/dashboard/store_orders'
    | '/dashboard/users'
    | '/dashboard/youtube'
    | '/developers/api'
    | '/docs/$slug'
    | '/events/$id'
    | '/judges/print'
    | '/locations/morgantown'
    | '/onshape/bom-history'
    | '/profile/$userId'
    | '/videos/$id'
    | '/academy/'
    | '/albums/'
    | '/blog/'
    | '/dashboard/'
    | '/docs/'
    | '/events/'
    | '/judges/'
    | '/locations/'
    | '/onshape/'
    | '/sponsors/'
    | '/videos/'
    | '/dashboard/blog/$editSlug'
    | '/dashboard/docs/$editSlug'
    | '/dashboard/event/$editId'
    | '/dashboard/manage_albums/$id'
    | '/dashboard/seasons/$editId'
    | '/dashboard/tasks/$taskId'
    | '/sponsors/roi/$tokenId'
    | '/dashboard/blog/'
    | '/dashboard/docs/'
    | '/dashboard/event/'
    | '/dashboard/seasons/'
    | '/dashboard/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  BugReportRoute: typeof BugReportRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  JoinRoute: typeof JoinRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  OutreachRoute: typeof OutreachRoute
  PrivacyRoute: typeof PrivacyRoute
  SeasonsRoute: typeof SeasonsRoute
  SimRunnerRoute: typeof SimRunnerRoute
  StoreRoute: typeof StoreRoute
  TechStackRoute: typeof TechStackRoute
  TermsRoute: typeof TermsRoute
  AcademySlugRoute: typeof AcademySlugRoute
  AlbumsIdRoute: typeof AlbumsIdRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DevelopersApiRoute: typeof DevelopersApiRoute
  DocsSlugRoute: typeof DocsSlugRoute
  EventsIdRoute: typeof EventsIdRoute
  JudgesPrintRoute: typeof JudgesPrintRoute
  LocationsMorgantownRoute: typeof LocationsMorgantownRoute
  OnshapeBomHistoryRoute: typeof OnshapeBomHistoryRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  VideosIdRoute: typeof VideosIdRoute
  AcademyIndexRoute: typeof AcademyIndexRoute
  AlbumsIndexRoute: typeof AlbumsIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  JudgesIndexRoute: typeof JudgesIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  OnshapeIndexRoute: typeof OnshapeIndexRoute
  SponsorsIndexRoute: typeof SponsorsIndexRoute
  VideosIndexRoute: typeof VideosIndexRoute
  SponsorsRoiTokenIdRoute: typeof SponsorsRoiTokenIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech-stack': {
      id: '/tech-stack'
      path: '/tech-stack'
      fullPath: '/tech-stack'
      preLoaderRoute: typeof TechStackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sim-runner': {
      id: '/sim-runner'
      path: '/sim-runner'
      fullPath: '/sim-runner'
      preLoaderRoute: typeof SimRunnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons': {
      id: '/seasons'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof SeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bug-report': {
      id: '/bug-report'
      path: '/bug-report'
      fullPath: '/bug-report'
      preLoaderRoute: typeof BugReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/videos'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors/': {
      id: '/sponsors/'
      path: '/sponsors'
      fullPath: '/sponsors/'
      preLoaderRoute: typeof SponsorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onshape/': {
      id: '/onshape/'
      path: '/onshape'
      fullPath: '/onshape/'
      preLoaderRoute: typeof OnshapeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judges/': {
      id: '/judges/'
      path: '/judges'
      fullPath: '/judges/'
      preLoaderRoute: typeof JudgesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/': {
      id: '/albums/'
      path: '/albums'
      fullPath: '/albums/'
      preLoaderRoute: typeof AlbumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/': {
      id: '/academy/'
      path: '/academy'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/$id': {
      id: '/videos/$id'
      path: '/videos/$id'
      fullPath: '/videos/$id'
      preLoaderRoute: typeof VideosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onshape/bom-history': {
      id: '/onshape/bom-history'
      path: '/onshape/bom-history'
      fullPath: '/onshape/bom-history'
      preLoaderRoute: typeof OnshapeBomHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/morgantown': {
      id: '/locations/morgantown'
      path: '/locations/morgantown'
      fullPath: '/locations/morgantown'
      preLoaderRoute: typeof LocationsMorgantownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judges/print': {
      id: '/judges/print'
      path: '/judges/print'
      fullPath: '/judges/print'
      preLoaderRoute: typeof JudgesPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/api': {
      id: '/developers/api'
      path: '/developers/api'
      fullPath: '/developers/api'
      preLoaderRoute: typeof DevelopersApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/youtube': {
      id: '/dashboard/youtube'
      path: '/youtube'
      fullPath: '/dashboard/youtube'
      preLoaderRoute: typeof DashboardYoutubeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/store_orders': {
      id: '/dashboard/store_orders'
      path: '/store_orders'
      fullPath: '/dashboard/store_orders'
      preLoaderRoute: typeof DashboardStore_ordersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sponsors': {
      id: '/dashboard/sponsors'
      path: '/sponsors'
      fullPath: '/dashboard/sponsors'
      preLoaderRoute: typeof DashboardSponsorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sponsor_tokens': {
      id: '/dashboard/sponsor_tokens'
      path: '/sponsor_tokens'
      fullPath: '/dashboard/sponsor_tokens'
      preLoaderRoute: typeof DashboardSponsor_tokensRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/social': {
      id: '/dashboard/social'
      path: '/social'
      fullPath: '/dashboard/social'
      preLoaderRoute: typeof DashboardSocialRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/simulations': {
      id: '/dashboard/simulations'
      path: '/simulations'
      fullPath: '/dashboard/simulations'
      preLoaderRoute: typeof DashboardSimulationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sims': {
      id: '/dashboard/sims'
      path: '/sims'
      fullPath: '/dashboard/sims'
      preLoaderRoute: typeof DashboardSimsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/scouting': {
      id: '/dashboard/scouting'
      path: '/scouting'
      fullPath: '/dashboard/scouting'
      preLoaderRoute: typeof DashboardScoutingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/photos': {
      id: '/dashboard/photos'
      path: '/photos'
      fullPath: '/dashboard/photos'
      preLoaderRoute: typeof DashboardPhotosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/outreach': {
      id: '/dashboard/outreach'
      path: '/outreach'
      fullPath: '/dashboard/outreach'
      preLoaderRoute: typeof DashboardOutreachRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mass_email': {
      id: '/dashboard/mass_email'
      path: '/mass_email'
      fullPath: '/dashboard/mass_email'
      preLoaderRoute: typeof DashboardMass_emailRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/manage_seasons': {
      id: '/dashboard/manage_seasons'
      path: '/manage_seasons'
      fullPath: '/dashboard/manage_seasons'
      preLoaderRoute: typeof DashboardManage_seasonsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/manage_event': {
      id: '/dashboard/manage_event'
      path: '/manage_event'
      fullPath: '/dashboard/manage_event'
      preLoaderRoute: typeof DashboardManage_eventRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/manage_docs': {
      id: '/dashboard/manage_docs'
      path: '/manage_docs'
      fullPath: '/dashboard/manage_docs'
      preLoaderRoute: typeof DashboardManage_docsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/manage_blog': {
      id: '/dashboard/manage_blog'
      path: '/manage_blog'
      fullPath: '/dashboard/manage_blog'
      preLoaderRoute: typeof DashboardManage_blogRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/manage_albums': {
      id: '/dashboard/manage_albums'
      path: '/manage_albums'
      fullPath: '/dashboard/manage_albums'
      preLoaderRoute: typeof DashboardManage_albumsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logistics': {
      id: '/dashboard/logistics'
      path: '/logistics'
      fullPath: '/dashboard/logistics'
      preLoaderRoute: typeof DashboardLogisticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/locations': {
      id: '/dashboard/locations'
      path: '/locations'
      fullPath: '/dashboard/locations'
      preLoaderRoute: typeof DashboardLocationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/legacy': {
      id: '/dashboard/legacy'
      path: '/legacy'
      fullPath: '/dashboard/legacy'
      preLoaderRoute: typeof DashboardLegacyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/judge_codes': {
      id: '/dashboard/judge_codes'
      path: '/judge_codes'
      fullPath: '/dashboard/judge_codes'
      preLoaderRoute: typeof DashboardJudge_codesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/integrations': {
      id: '/dashboard/integrations'
      path: '/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof DashboardIntegrationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inquiries': {
      id: '/dashboard/inquiries'
      path: '/inquiries'
      fullPath: '/dashboard/inquiries'
      preLoaderRoute: typeof DashboardInquiriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/impact_roster': {
      id: '/dashboard/impact_roster'
      path: '/impact_roster'
      fullPath: '/dashboard/impact_roster'
      preLoaderRoute: typeof DashboardImpact_rosterRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gmail': {
      id: '/dashboard/gmail'
      path: '/gmail'
      fullPath: '/dashboard/gmail'
      preLoaderRoute: typeof DashboardGmailRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/finance': {
      id: '/dashboard/finance'
      path: '/finance'
      fullPath: '/dashboard/finance'
      preLoaderRoute: typeof DashboardFinanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/files': {
      id: '/dashboard/files'
      path: '/files'
      fullPath: '/dashboard/files'
      preLoaderRoute: typeof DashboardFilesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/drive-docs': {
      id: '/dashboard/drive-docs'
      path: '/drive-docs'
      fullPath: '/dashboard/drive-docs'
      preLoaderRoute: typeof DashboardDriveDocsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/db_studio': {
      id: '/dashboard/db_studio'
      path: '/db_studio'
      fullPath: '/dashboard/db_studio'
      preLoaderRoute: typeof DashboardDb_studioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/command_center': {
      id: '/dashboard/command_center'
      path: '/command_center'
      fullPath: '/dashboard/command_center'
      preLoaderRoute: typeof DashboardCommand_centerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/badges': {
      id: '/dashboard/badges'
      path: '/badges'
      fullPath: '/dashboard/badges'
      preLoaderRoute: typeof DashboardBadgesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assets': {
      id: '/dashboard/assets'
      path: '/assets'
      fullPath: '/dashboard/assets'
      preLoaderRoute: typeof DashboardAssetsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$id': {
      id: '/albums/$id'
      path: '/albums/$id'
      fullPath: '/albums/$id'
      preLoaderRoute: typeof AlbumsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/$slug': {
      id: '/academy/$slug'
      path: '/academy/$slug'
      fullPath: '/academy/$slug'
      preLoaderRoute: typeof AcademySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tasks/': {
      id: '/dashboard/tasks/'
      path: '/tasks'
      fullPath: '/dashboard/tasks/'
      preLoaderRoute: typeof DashboardTasksIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/seasons/': {
      id: '/dashboard/seasons/'
      path: '/seasons'
      fullPath: '/dashboard/seasons/'
      preLoaderRoute: typeof DashboardSeasonsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/event/': {
      id: '/dashboard/event/'
      path: '/event'
      fullPath: '/dashboard/event/'
      preLoaderRoute: typeof DashboardEventIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/docs/': {
      id: '/dashboard/docs/'
      path: '/docs'
      fullPath: '/dashboard/docs/'
      preLoaderRoute: typeof DashboardDocsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/blog/': {
      id: '/dashboard/blog/'
      path: '/blog'
      fullPath: '/dashboard/blog/'
      preLoaderRoute: typeof DashboardBlogIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/sponsors/roi/$tokenId': {
      id: '/sponsors/roi/$tokenId'
      path: '/sponsors/roi/$tokenId'
      fullPath: '/sponsors/roi/$tokenId'
      preLoaderRoute: typeof SponsorsRoiTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tasks/$taskId': {
      id: '/dashboard/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/dashboard/tasks/$taskId'
      preLoaderRoute: typeof DashboardTasksTaskIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/seasons/$editId': {
      id: '/dashboard/seasons/$editId'
      path: '/seasons/$editId'
      fullPath: '/dashboard/seasons/$editId'
      preLoaderRoute: typeof DashboardSeasonsEditIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/manage_albums/$id': {
      id: '/dashboard/manage_albums/$id'
      path: '/$id'
      fullPath: '/dashboard/manage_albums/$id'
      preLoaderRoute: typeof DashboardManage_albumsIdRouteImport
      parentRoute: typeof DashboardManage_albumsRoute
    }
    '/dashboard/event/$editId': {
      id: '/dashboard/event/$editId'
      path: '/event/$editId'
      fullPath: '/dashboard/event/$editId'
      preLoaderRoute: typeof DashboardEventEditIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/docs/$editSlug': {
      id: '/dashboard/docs/$editSlug'
      path: '/docs/$editSlug'
      fullPath: '/dashboard/docs/$editSlug'
      preLoaderRoute: typeof DashboardDocsEditSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/blog/$editSlug': {
      id: '/dashboard/blog/$editSlug'
      path: '/blog/$editSlug'
      fullPath: '/dashboard/blog/$editSlug'
      preLoaderRoute: typeof DashboardBlogEditSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardManage_albumsRouteChildren {
  DashboardManage_albumsIdRoute: typeof DashboardManage_albumsIdRoute
}

const DashboardManage_albumsRouteChildren: DashboardManage_albumsRouteChildren =
  {
    DashboardManage_albumsIdRoute: DashboardManage_albumsIdRoute,
  }

const DashboardManage_albumsRouteWithChildren =
  DashboardManage_albumsRoute._addFileChildren(
    DashboardManage_albumsRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardAssetsRoute: typeof DashboardAssetsRoute
  DashboardBadgesRoute: typeof DashboardBadgesRoute
  DashboardCommand_centerRoute: typeof DashboardCommand_centerRoute
  DashboardDb_studioRoute: typeof DashboardDb_studioRoute
  DashboardDriveDocsRoute: typeof DashboardDriveDocsRoute
  DashboardFilesRoute: typeof DashboardFilesRoute
  DashboardFinanceRoute: typeof DashboardFinanceRoute
  DashboardGmailRoute: typeof DashboardGmailRoute
  DashboardImpact_rosterRoute: typeof DashboardImpact_rosterRoute
  DashboardInquiriesRoute: typeof DashboardInquiriesRoute
  DashboardIntegrationsRoute: typeof DashboardIntegrationsRoute
  DashboardJudge_codesRoute: typeof DashboardJudge_codesRoute
  DashboardLegacyRoute: typeof DashboardLegacyRoute
  DashboardLocationsRoute: typeof DashboardLocationsRoute
  DashboardLogisticsRoute: typeof DashboardLogisticsRoute
  DashboardManage_albumsRoute: typeof DashboardManage_albumsRouteWithChildren
  DashboardManage_blogRoute: typeof DashboardManage_blogRoute
  DashboardManage_docsRoute: typeof DashboardManage_docsRoute
  DashboardManage_eventRoute: typeof DashboardManage_eventRoute
  DashboardManage_seasonsRoute: typeof DashboardManage_seasonsRoute
  DashboardMass_emailRoute: typeof DashboardMass_emailRoute
  DashboardOutreachRoute: typeof DashboardOutreachRoute
  DashboardPhotosRoute: typeof DashboardPhotosRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardScoutingRoute: typeof DashboardScoutingRoute
  DashboardSimsRoute: typeof DashboardSimsRoute
  DashboardSimulationsRoute: typeof DashboardSimulationsRoute
  DashboardSocialRoute: typeof DashboardSocialRoute
  DashboardSponsor_tokensRoute: typeof DashboardSponsor_tokensRoute
  DashboardSponsorsRoute: typeof DashboardSponsorsRoute
  DashboardStore_ordersRoute: typeof DashboardStore_ordersRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardYoutubeRoute: typeof DashboardYoutubeRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBlogEditSlugRoute: typeof DashboardBlogEditSlugRoute
  DashboardDocsEditSlugRoute: typeof DashboardDocsEditSlugRoute
  DashboardEventEditIdRoute: typeof DashboardEventEditIdRoute
  DashboardSeasonsEditIdRoute: typeof DashboardSeasonsEditIdRoute
  DashboardTasksTaskIdRoute: typeof DashboardTasksTaskIdRoute
  DashboardBlogIndexRoute: typeof DashboardBlogIndexRoute
  DashboardDocsIndexRoute: typeof DashboardDocsIndexRoute
  DashboardEventIndexRoute: typeof DashboardEventIndexRoute
  DashboardSeasonsIndexRoute: typeof DashboardSeasonsIndexRoute
  DashboardTasksIndexRoute: typeof DashboardTasksIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardAssetsRoute: DashboardAssetsRoute,
  DashboardBadgesRoute: DashboardBadgesRoute,
  DashboardCommand_centerRoute: DashboardCommand_centerRoute,
  DashboardDb_studioRoute: DashboardDb_studioRoute,
  DashboardDriveDocsRoute: DashboardDriveDocsRoute,
  DashboardFilesRoute: DashboardFilesRoute,
  DashboardFinanceRoute: DashboardFinanceRoute,
  DashboardGmailRoute: DashboardGmailRoute,
  DashboardImpact_rosterRoute: DashboardImpact_rosterRoute,
  DashboardInquiriesRoute: DashboardInquiriesRoute,
  DashboardIntegrationsRoute: DashboardIntegrationsRoute,
  DashboardJudge_codesRoute: DashboardJudge_codesRoute,
  DashboardLegacyRoute: DashboardLegacyRoute,
  DashboardLocationsRoute: DashboardLocationsRoute,
  DashboardLogisticsRoute: DashboardLogisticsRoute,
  DashboardManage_albumsRoute: DashboardManage_albumsRouteWithChildren,
  DashboardManage_blogRoute: DashboardManage_blogRoute,
  DashboardManage_docsRoute: DashboardManage_docsRoute,
  DashboardManage_eventRoute: DashboardManage_eventRoute,
  DashboardManage_seasonsRoute: DashboardManage_seasonsRoute,
  DashboardMass_emailRoute: DashboardMass_emailRoute,
  DashboardOutreachRoute: DashboardOutreachRoute,
  DashboardPhotosRoute: DashboardPhotosRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardScoutingRoute: DashboardScoutingRoute,
  DashboardSimsRoute: DashboardSimsRoute,
  DashboardSimulationsRoute: DashboardSimulationsRoute,
  DashboardSocialRoute: DashboardSocialRoute,
  DashboardSponsor_tokensRoute: DashboardSponsor_tokensRoute,
  DashboardSponsorsRoute: DashboardSponsorsRoute,
  DashboardStore_ordersRoute: DashboardStore_ordersRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardYoutubeRoute: DashboardYoutubeRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBlogEditSlugRoute: DashboardBlogEditSlugRoute,
  DashboardDocsEditSlugRoute: DashboardDocsEditSlugRoute,
  DashboardEventEditIdRoute: DashboardEventEditIdRoute,
  DashboardSeasonsEditIdRoute: DashboardSeasonsEditIdRoute,
  DashboardTasksTaskIdRoute: DashboardTasksTaskIdRoute,
  DashboardBlogIndexRoute: DashboardBlogIndexRoute,
  DashboardDocsIndexRoute: DashboardDocsIndexRoute,
  DashboardEventIndexRoute: DashboardEventIndexRoute,
  DashboardSeasonsIndexRoute: DashboardSeasonsIndexRoute,
  DashboardTasksIndexRoute: DashboardTasksIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  BugReportRoute: BugReportRoute,
  DashboardRoute: DashboardRouteWithChildren,
  GalleryRoute: GalleryRoute,
  JoinRoute: JoinRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  OutreachRoute: OutreachRoute,
  PrivacyRoute: PrivacyRoute,
  SeasonsRoute: SeasonsRoute,
  SimRunnerRoute: SimRunnerRoute,
  StoreRoute: StoreRoute,
  TechStackRoute: TechStackRoute,
  TermsRoute: TermsRoute,
  AcademySlugRoute: AcademySlugRoute,
  AlbumsIdRoute: AlbumsIdRoute,
  BlogSlugRoute: BlogSlugRoute,
  DevelopersApiRoute: DevelopersApiRoute,
  DocsSlugRoute: DocsSlugRoute,
  EventsIdRoute: EventsIdRoute,
  JudgesPrintRoute: JudgesPrintRoute,
  LocationsMorgantownRoute: LocationsMorgantownRoute,
  OnshapeBomHistoryRoute: OnshapeBomHistoryRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  VideosIdRoute: VideosIdRoute,
  AcademyIndexRoute: AcademyIndexRoute,
  AlbumsIndexRoute: AlbumsIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  JudgesIndexRoute: JudgesIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  OnshapeIndexRoute: OnshapeIndexRoute,
  SponsorsIndexRoute: SponsorsIndexRoute,
  VideosIndexRoute: VideosIndexRoute,
  SponsorsRoiTokenIdRoute: SponsorsRoiTokenIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
